### ISSUE TITLE
Getaddrinfo() failed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/mythbox#103]
```
My backend and database are on a different host (64 bit gentoo)

On a windows 7 32 bit client, when trying to play a recording or livetv, I get 
the following log.  (My recording dir is set to u: - a mapped network drive 
which holds all my recordings)

---
22:03:10 T:5344 M:1395073024   ERROR: DIRECTORY::CDirectory::GetDirectory - 
Error getting ?
22:03:10 T:5344 M:1395073024   ERROR: CGUIMediaWindow::GetDirectory(?) failed
22:03:11 T:6736 M:1395421184  NOTICE: ERROR | mythbox.core | util.py | Line 390 
| CATCHALL_UI: Caught exception (11004, 'getaddrinfo failed') on method 
<function onInit at 0x0AB20B70>
                                            Traceback (most recent call last):
                                              File "C:\Users\Chris\AppData\Roaming\XBMC\scripts\MythBox\resources\src\mythbox\util.py", line 388, in catchall_ui
                                                return func(*args, **kw)
                                              File "C:\Users\Chris\AppData\Roaming\XBMC\scripts\MythBox\resources\src\mythbox\ui\recordingdetails.py", line 74, in onInit
                                                self.render()
                                              File "<string>", line 1, in <lambda>
                                              File "C:\Users\Chris\AppData\Roaming\XBMC\scripts\MythBox\resources\src\mythbox\ui\toolkit.py", line 193, in window_busy
                                                result = func(*args, **kwargs)
                                              File "C:\Users\Chris\AppData\Roaming\XBMC\scripts\MythBox\resources\src\mythbox\ui\recordingdetails.py", line 207, in render
                                                self.renderThumbnail()
                                              File "C:\Users\Chris\AppData\Roaming\XBMC\scripts\MythBox\resources\src\mythbox\ui\recordingdetails.py", line 261, in renderThumbnail
                                                thumbFile = self.mythThumbnailCache.get(self.program)
                                              File "C:\Users\Chris\AppData\Roaming\XBMC\scripts\MythBox\resources\src\mythbox\filecache.py", line 92, in get
                                                self.resolver.store(fileUrl, filepath)
                                              File "<string>", line 1, in <lambda>
                                              File "C:\Users\Chris\AppData\Roaming\XBMC\scripts\MythBox\resources\src\mythbox\mythtv\conn.py", line 119, in inject_conn
                                                result = func(*args, **kwargs)
                                              File "C:\Users\Chris\AppData\Roaming\XBMC\scripts\MythBox\resources\src\mythbox\mythtv\resolver.py", line 45, in store
                                                result = self.conn().transferFile(key, dest, program.hostname())
                                              File "C:\Users\Chris\AppData\Roaming\XBMC\scripts\MythBox\resources\src\mythbox\mythtv\conn.py", line 1049, in transferFile
                                                commandSocket = self.connect(announce='Playback', slaveBackend=backendHost)
                                              File "C:\Users\Chris\AppData\Roaming\XBMC\scripts\MythBox\resources\src\mythbox\mythtv\conn.py", line 173, in connect
                                                s.connect((slaveBackend, self.port))
                                              File "<string>", line 1, in connect
                                            gaierror: (11004, 'getaddrinfo failed')
22:03:11 T:6736 M:1395417088  NOTICE: .
22:03:14 T:6736 M:1395265536  NOTICE: ERROR | mythbox.core | util.py | Line 390 
| CATCHALL_UI: Caught exception (11004, 'getaddrinfo failed') on method 
<function onClick at 0x0AAD2AF0>
                                            Traceback (most recent call last):
                                              File "C:\Users\Chris\AppData\Roaming\XBMC\scripts\MythBox\resources\src\mythbox\util.py", line 388, in catchall_ui
                                                return func(*args, **kw)
                                              File "<string>", line 1, in <lambda>
                                              File "C:\Users\Chris\AppData\Roaming\XBMC\scripts\MythBox\resources\src\mythbox\util.py", line 201, in lirc_hack
                                                return func(*args, **kwargs)
                                              File "<string>", line 1, in <lambda>
                                              File "C:\Users\Chris\AppData\Roaming\XBMC\scripts\MythBox\resources\src\mythbox\ui\toolkit.py", line 193, in window_busy
                                                result = func(*args, **kwargs)
                                              File "C:\Users\Chris\AppData\Roaming\XBMC\scripts\MythBox\resources\src\mythbox\ui\recordingdetails.py", line 191, in onClick
                                                self.dispatcher[source.getId()]()
                                              File "C:\Users\Chris\AppData\Roaming\XBMC\scripts\MythBox\resources\src\mythbox\ui\recordingdetails.py", line 128, in play
                                                p.playRecording(self.program, NoOpCommercialSkipper(p, self.program))
                                              File "C:\Users\Chris\AppData\Roaming\XBMC\scripts\MythBox\resources\src\mythbox\ui\player.py", line 72, in playRecording
                                                self.play(self.getFileUrl(), self._buildPlayList())
                                              File "C:\Users\Chris\AppData\Roaming\XBMC\scripts\MythBox\resources\src\mythbox\ui\player.py", line 158, in _buildPlayList
                                                playlistItem.setIconImage(self.mythThumbnailCache.get(self._program))
                                              File "C:\Users\Chris\AppData\Roaming\XBMC\scripts\MythBox\resources\src\mythbox\filecache.py", line 92, in get
                                                self.resolver.store(fileUrl, filepath)
                                              File "<string>", line 1, in <lambda>
                                              File "C:\Users\Chris\AppData\Roaming\XBMC\scripts\MythBox\resources\src\mythbox\mythtv\conn.py", line 119, in inject_conn
                                                result = func(*args, **kwargs)
                                              File "C:\Users\Chris\AppData\Roaming\XBMC\scripts\MythBox\resources\src\mythbox\mythtv\resolver.py", line 45, in store
                                                result = self.conn().transferFile(key, dest, program.hostname())
                                              File "C:\Users\Chris\AppData\Roaming\XBMC\scripts\MythBox\resources\src\mythbox\mythtv\conn.py", line 1049, in transferFile
                                                commandSocket = self.connect(announce='Playback', slaveBackend=backendHost)
                                              File "C:\Users\Chris\AppData\Roaming\XBMC\scripts\MythBox\resources\src\mythbox\mythtv\conn.py", line 173, in connect
                                                s.connect((slaveBackend, self.port))
                                              File "<string>", line 1, in connect
                                            gaierror: (11004, 'getaddrinfo failed')
22:03:14 T:6736 M:1395261440  NOTICE: .
22:03:16 T:5344 M:1396412416   ERROR: DIRECTORY::CDirectory::GetDirectory - 
Error getting ?
22:03:16 T:5344 M:1396412416   ERROR: CGUIMediaWindow::GetDirectory(?) failed
22:03:19 T:5344 M:1396047872   ERROR: CLocalizeStrings::ClearBlock: Trying to 
clear non existent block C:\Users\Chris\AppData\Roaming\XBMC\scripts\MythBox
22:03:19 T:5344 M:1396035584   ERROR: DIRECTORY::CDirectory::GetDirectory - 
Error getting ?
22:03:19 T:5344 M:1396035584   ERROR: CGUIMediaWindow::GetDirectory(?) failed


```

Original issue reported on code.google.com by `iwouldra...@gmail.com` on 30 Jun 2010 at 8:06
- Merged into: #98

**Comment by GoogleCodeExporter** [comment]
```
As in bug 102, adding the hostname of the server to my hosts file in windows 
fixed this problem

However, I don't reference this hostname anywhere in mythtv - I use IP 
addresses for everything, so the requirement for it is a bit puzzling.

The error message could be updated to indicate which address is failing to 
resolve.
```

Original comment by `iwouldra...@gmail.com` on 30 Jun 2010 at 8:14

**Comment by GoogleCodeExporter** [comment]
```
Same basic problem as pointed out in Issue 98. Please try the version from 
comment 6.
```

Original comment by `semir.pa...@gmail.com` on 12 Jul 2010 at 7:05
- Changed state: **Duplicate**
