### ISSUE TITLE
Error on boot when no script_data folder.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/mythbox#137]
```
What steps will reproduce the problem?
1. Clean install of XBMC.
2. Install MythBox
3. Start MythBox

What is the expected output? What do you see instead?
Mythbox should give the usual message that it should be set up. Instead, the 
log provides the following:

INFO | mythbox.core | __init__.py | MainThread | Line 1072 | Mythbox Logger 
Initialized
ERROR | mythbox.core | __init__.py | MainThread | Line 1072 | [Errno 2] No such 
file or directory: '/Users/jeff/Library/Application 
Support/XBMC/userdata/script_data/script.mythbox'
Traceback (most recent call last):
  File "/Users/jeff/Library/Application Support/XBMC/addons/script.mythbox/resources/src/mythbox/bootstrapper.py", line 41, in run
    self.bootstrapPlatform()
  File "/Users/jeff/Library/Application Support/XBMC/addons/script.mythbox/resources/src/mythbox/bootstrapper.py", line 81, in bootstrapPlatform
    self.platform = mythbox.platform.getPlatform()
  File "~/Library/Application Support/XBMC/addons/script.mythbox/resources/src/mythbox/platform.py", line 38, in getPlatform
    __instance = MacPlatform()
  File "/Users/jeff/Library/Application Support/XBMC/addons/script.mythbox/resources/src/mythbox/platform.py", line 53, in __init__
    os.mkdir(datadir)
OSError: [Errno 2] No such file or directory: '~/Library/Application 
Support/XBMC/userdata/script_data/script.mythbox'


What version of the product are you using? On what operating system?
Mac OS X 10.6.5
Dharma RC1
MythBox R1370996e1e

Please provide any additional information below.
Creating ~/Library/Application Support/XBMC/userdata/script_data eliminates 
this error. Perhaps mythbox should create this folder if it's not there yet?
```

Original issue reported on code.google.com by `hentsche...@gmail.com` on 7 Dec 2010 at 3:25

**Comment by GoogleCodeExporter** [comment]
```
I believe this was a problem in dharma RC1. Please retry in dharma RC2. Also, 
you should probably delete the following directories as they are remnants from 
the previous version of xbmc.

/Users/jeff/Library/Application Support/XBMC/scripts
/Users/jeff/Library/Application Support/XBMC/userdata/script_data

They have been replaced with addons and addon_data respectively.
```

Original comment by `semir.pa...@gmail.com` on 14 Dec 2010 at 3:16

**Comment by GoogleCodeExporter** [comment]
```
Re-open if this is still a problem under Dharma (script_data is a Camelot thing)
```

Original comment by `semir.pa...@gmail.com` on 20 Jan 2011 at 5:17
- Changed state: **Invalid**
