### ISSUE TITLE
 'ascii' codec can't encode character u'\u0105' 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/mythbox#145]
```
I add debug xbmc.log problems with polish encodings and attached mythbox.log.


1.


22:56:37 T:3078223744 M:2557300736   DEBUG: ------ Window Init 
(/home/marcin/.xbmc/addons/script.mythbox/resources/skins/Default/720p/mythbox_t
vguide.xml) ------
22:56:37 T:3078223744 M:2557300736    INFO: Loading skin file: 
/home/marcin/.xbmc/addons/script.mythbox/resources/skins/Default/720p/mythbox_tv
guide.xml
22:56:37 T:3078223744 M:2557263872   DEBUG: SDLKeyboard: scancode: 116, sym: 
274, unicode: 0, modifier: 0
22:56:37 T:3078223744 M:2557263872   DEBUG: OnKey: 61480 pressed, action is Down
22:56:38 T:3078223744 M:2557562880   DEBUG: SDLKeyboard: scancode: 36, sym: 13, 
unicode: 13, modifier: 0
22:56:38 T:3078223744 M:2557562880   DEBUG: OnKey: 61453 pressed, action is 
Select
22:56:38 T:2901592944 M:2557390848  NOTICE: ERROR | mythbox.ui | tvguide.py | 
MainThread | Line 328 | 'ascii' codec can't encode character u'\u0105' in 
position 18: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/marcin/.xbmc/addons/script.mythbox/resources/src/mythbox/ui/tvguide.py", line 326, in watchLiveTv
                                                brain.watchLiveTV(channel)
                                              File "/home/marcin/.xbmc/addons/script.mythbox/resources/src/mythbox/ui/livetv.py", line 87, in watchLiveTV
                                                xbmcgui.Dialog().ok(self.translator.get(m.INFO), str(se))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\u0105' in position 18: ordinal not in range(128)
22:56:38 T:2901592944 M:2557390848  NOTICE: .
22:56:38 T:2901592944 M:2557169664    INFO: Loading skin file: DialogOK.xml



2.


22:55:12 T:2901592944 M:2561490944  NOTICE: ERROR | mythbox.ui | tvguide.py | 
MainThread | Line 328 | 'ascii' codec can't encode character u'\u0105' in 
position 18: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/marcin/.xbmc/addons/script.mythbox/resources/src/mythbox/ui/tvguide.py", line 326, in watchLiveTv
                                                brain.watchLiveTV(channel)
                                              File "/home/marcin/.xbmc/addons/script.mythbox/resources/src/mythbox/ui/livetv.py", line 87, in watchLiveTV
                                                xbmcgui.Dialog().ok(self.translator.get(m.INFO), str(se))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\u0105' in position 18: ordinal not in range(128)
22:55:12 T:2901592944 M:2561490944  NOTICE: .


Thanks in advance for fix it.

```

Original issue reported on code.google.com by `marcin.j...@gmail.com` on 13 Jan 2011 at 10:01

Attachments:
- [mythbox.log](https://storage.googleapis.com/google-code-attachments/mythbox/issue-145/comment-0/mythbox.log)

**Comment by GoogleCodeExporter** [comment]
```
Fixed in revision b71e61061f
```

Original comment by `semir.pa...@gmail.com` on 20 Jan 2011 at 4:47
- Changed state: **Fixed**
