### ISSUE TITLE
When i run channel without EPG i cannot open it :(

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/mythbox#146]
```
ERROR | imdbpy.parser.http.domparser | utils.py | Thread-46 | Line 528 | 
DOMHTMLMovieParser: caught exception extracting XPath 
"//div[@id='tn15title']//span[starts-with(text(), 'TV series')]"
Traceback (most recent call last):
  File "/home/marcin/.xbmc/addons/script.mythbox/resources/lib/IMDbPY/imdb/parser/http/utils.py", line 517, in xpath
    xpath_result = element.xpath(path)
  File "/home/marcin/.xbmc/addons/script.mythbox/resources/lib/IMDbPY/imdb/parser/http/bsouplxml/etree.py", line 57, in xpath
    return path.apply(node)
  File "/home/marcin/.xbmc/addons/script.mythbox/resources/lib/IMDbPY/imdb/parser/http/bsouplxml/bsoupxpath.py", line 113, in apply
    nodes = step.apply(nodes)
  File "/home/marcin/.xbmc/addons/script.mythbox/resources/lib/IMDbPY/imdb/parser/http/bsouplxml/bsoupxpath.py", line 287, in apply
    found = filter(checker, found)
  File "/home/marcin/.xbmc/addons/script.mythbox/resources/lib/IMDbPY/imdb/parser/http/bsouplxml/bsoupxpath.py", line 331, in __call__
    return self.__filter(node)
  File "/home/marcin/.xbmc/addons/script.mythbox/resources/lib/IMDbPY/imdb/parser/http/bsouplxml/bsoupxpath.py", line 360, in __starts_with
    first = node.contents[0]
IndexError: list index out of range
WARNING | imdbpy.parser.http.domparser | utils.py | Thread-46 | Line 423 | 
unable to use "lxml": No module named lxml.html
WARNING | imdbpy.parser.http.domparser | utils.py | Thread-46 | Line 414 | 
falling back to "beautifulsoup"
WARNING | mythbox.fanart | fanart.py | Thread-46 | Line 407 | TVDB errored out 
on "Pasmo nocne" with error "Show-name search returned zero results (cannot 
find show on TVDB)"
WARNING | mythbox.fanart | fanart.py | Thread-46 | Line 407 | TVDB errored out 
on "sportaktuell" with error "Show-name search returned zero results (cannot 
find show on TVDB)"
WARNING | mythbox.fanart | fanart.py | Thread-46 | Line 407 | TVDB errored out 
on "Porta a Porta" with error "Show-name search returned zero results (cannot 
find show on TVDB)"
WARNING | mythbox.fanart | fanart.py | Thread-46 | Line 407 | TVDB errored out 
on "Scrittori per un annoElsa Osorio" with error "Show-name search returned 
zero results (cannot find show on TVDB)"
```

Original issue reported on code.google.com by `marcin.j...@gmail.com` on 13 Jan 2011 at 10:40

**Comment by GoogleCodeExporter** [comment]
```
While your description does contain an error (in the IMDBpy library) it is not 
the error which is causing your problem. Please attach your xbmc.log or 
mythbox.log
```

Original comment by `semir.pa...@gmail.com` on 20 Jan 2011 at 4:48

**Comment by GoogleCodeExporter** [comment]
```
No log; Setting invalid
```

Original comment by `semir.pa...@gmail.com` on 27 Mar 2011 at 1:47
- Changed state: **Invalid**
