### ISSUE TITLE
ascii code can't encode character u'\u0161

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/mythbox#151]
```
What steps will reproduce the problem?
1. Open MythBox 
2. Select EPG
3. Select some program name with special czech character

Trace log:

nicodeEncodeError: 'ascii' codec can't encode character u'\u0161' in position 
1: ordinal not in range(128)
ERROR | mythbox.ui | tvguide.py | MainThread | Line 328 | 'ascii' codec can't 
encode character u'\u0161' in position 1: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/milosn/.xbmc/addons/script.mythbox/resources/src/mythbox/ui/tvguide.py", line 326, in watchLiveTv
    brain.watchLiveTV(channel)
  File "/home/milosn/.xbmc/addons/script.mythbox/resources/src/mythbox/ui/livetv.py", line 87, in watchLiveTV
    xbmcgui.Dialog().ok(self.translator.get(m.INFO), str(se))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0161' in position 
1: ordinal not in range(128)
ERROR | mythbox.ui | tvguide.py | MainThread | Line 328 | 'ascii' codec can't 
encode character u'\u0161' in position 1: ordinal not in range(128)
Traceback (most recent call last):

Mythbox version 1.0.1, XBMC 10

Thanks. Milos Novotny
```

Original issue reported on code.google.com by `nso...@gmail.com` on 22 Jan 2011 at 12:18

**Comment by GoogleCodeExporter** [comment]
```
Ahoj mám naprosto stejný problém jako ty, Pouzivam Mythbox 1.0.2 , nasel sji 
nekde reseni??cau Aleš
```

Original comment by `ales.oha...@gmail.com` on 11 Feb 2011 at 9:15

**Comment by GoogleCodeExporter** [comment]
```
Hi,
the solution is very easy - in the XBMC installation directory find the 
python24.zip which contains Python's standard library. Modify site.py file in 
this file - search for setencoding() function and modify the system's default 
encoding - the default is ascii, I have changed it to "utf-8" under Ubuntu 
10.10. Zip the file back and replace the original python24.zip . With this 
modification the current status of DVB cards is show correctly and commercial 
skipping works fine.

Regards,
Jan Svec
```

Original comment by `honza.svec` on 17 Mar 2011 at 11:24

**Comment by GoogleCodeExporter** [comment]
```
Please try again with the trunk release.
```

Original comment by `semir.pa...@gmail.com` on 27 Mar 2011 at 1:46
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `semir.pa...@gmail.com` on 30 Dec 2011 at 9:34
- Changed state: **Invalid**
