### ISSUE TITLE
Unable to view Upcoming Recordings

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/mythbox#181]
```
What steps will reproduce the problem?
1. Launch Mythbox
2. Select Upcoming Recordings
3.

What is the expected output? What do you see instead?
Expect to see a list of upcoming recordings.  Get a pop up error window which 
states "Error: OnInit 0" and an OK option, the area where the list of 
recordings should be is blank.

What version of the product are you using? On what operating system?
1.0.4 on Ubuntu 10.04 server (2.6.32-33) XBMC 10.04

Please provide any additional information below.
XBMC Debug log output

09:49:34 T:140507403114560 M:874614784   DEBUG: OnKey: 61453 pressed, action is 
Select
09:49:34 T:140506999015168 M:874487808    INFO: Default 4:3 resolution 
directory is 720p
09:49:34 T:140506999015168 M:874487808    INFO: Default 16:9 resolution 
directory is 720p
09:49:34 T:140506999015168 M:874487808    INFO: Loading skin includes from 
/720p/includes.xml
09:49:34 T:140506999015168 M:874487808    INFO: Error loading includes.xml file 
(/720p/includes.xml): Failed to open file (row=0, col=0)
09:49:34 T:140507403114560 M:874487808   DEBUG: Activating window ID: 13002
09:49:34 T:140507403114560 M:874487808   DEBUG: Checking if window ID 13002 is 
locked.
09:49:34 T:140507403114560 M:874487808   DEBUG: ------ Window Deinit 
(/home/bg/.xbmc/addons/script.mythbox/resources/skins/Default/720p/mythbox_home.
xml) ------
09:49:35 T:140507403114560 M:874487808   DEBUG: ------ Window Init 
(/home/bg/.xbmc/addons/script.mythbox/resources/skins/Default/720p/mythbox_upcom
ing.xml) ------
09:49:35 T:140507403114560 M:874487808    INFO: Loading skin file: 
/home/bg/.xbmc/addons/script.mythbox/resources/skins/Default/720p/mythbox_upcomi
ng.xml
09:49:35 T:140507403114560 M:874487808   DEBUG: SDLKeyboard: scancode: 64, sym: 
308, unicode: 0, modifier: 0
09:49:35 T:140506999015168 M:874487808  NOTICE: E | __init__.py | MainThread | 
Line 1072 | (<class exceptions.KeyError at 0x3bff0f0>, <exceptions.KeyError 
instance at 0x7fca500f6680>, <traceback object at 0x7fca500a8ff0>)
09:49:35 T:140506999015168 M:874487808  NOTICE: .
09:49:35 T:140506999015168 M:874528768  NOTICE: E | __init__.py | MainThread | 
Line 1072 | CATCHALL_UI: Caught <type 'instance'> exception 0 on method onInit
                                            Traceback (most recent call last):
                                              File "/home/bg/.xbmc/addons/script.mythbox/resources/src/mythbox/util.py", line 305, in catchall_ui
                                                return func(*args, **kw)
                                              File "/home/bg/.xbmc/addons/script.mythbox/resources/src/mythbox/ui/upcoming.py", line 72, in onInit
                                                self.refresh()
                                              File "<string>", line 1, in <lambda>
                                              File "/home/bg/.xbmc/addons/script.mythbox/resources/src/mythbox/ui/toolkit.py", line 196, in window_busy
                                                result = func(*args, **kwargs)
                                              File "/home/bg/.xbmc/addons/script.mythbox/resources/src/mythbox/ui/upcoming.py", line 149, in refresh
                                                self.applySort()
                                              File "/home/bg/.xbmc/addons/script.mythbox/resources/src/mythbox/ui/upcoming.py", line 90, in applySort
                                                self.render()
                                              File "<string>", line 1, in <lambda>
                                              File "/home/bg/.xbmc/addons/script.mythbox/resources/src/mythbox/mythtv/conn.py", line 122, in inject_conn
                                                result = func(*args, **kwargs)
                                              File "<string>", line 1, in <lambda>
                                              File "/home/bg/.xbmc/addons/script.mythbox/resources/src/mythbox/util.py", line 256, in ui_locked
                                                result = func(*args, **kw)
                                              File "/home/bg/.xbmc/addons/script.mythbox/resources/src/mythbox/ui/upcoming.py", line 185, in render
                                                buildListItems()
                                              File "<string>", line 1, in <lambda>
                                              File "/home/bg/.xbmc/addons/script.mythbox/resources/src/mythbox/util.py", line 278, in ui_locked2
                                                result = func(*args, **kw)
                                              File "/home/bg/.xbmc/addons/script.mythbox/resources/src/mythbox/ui/upcoming.py", line 177, in buildListItems
                                                tuner = self.tunersById[p.getTunerId()]
                                            KeyError: 0
09:49:35 T:140506999015168 M:874528768  NOTICE: .
09:49:35 T:140506999015168 M:874561536    INFO: Loading skin file: DialogOK.xml
09:49:35 T:140507403114560 M:874561536   DEBUG: ------ Window Init 
(DialogOK.xml) ------
```

Original issue reported on code.google.com by `barrygoo...@gmail.com` on 10 Sep 2011 at 9:23

**Comment by GoogleCodeExporter** [comment]
```
Forgot to add, I'm using the Transparency skin.
```

Original comment by `barrygoo...@gmail.com` on 10 Sep 2011 at 9:28

**Comment by GoogleCodeExporter** [comment]
```
The latest Mythtv update seems to have resolved this, it's now working as 
expected :)
```

Original comment by `barrygoo...@gmail.com` on 22 Sep 2011 at 10:59

**Comment by GoogleCodeExporter** [comment]
Original comment by `semir.pa...@gmail.com` on 31 Dec 2011 at 5:44
- Changed state: **WontFix**
