### ISSUE TITLE
onInit error at start

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/mythbox#188]
```
What steps will reproduce the problem?
1. Install Fedora 15.
2. Install XBMC from rpmfusion
3. Install MythBox via Add-ons in XBMC

What is the expected output? What do you see instead?
A window pops up:

Error: OnInit
OnInit
with an OK button

This occurs before and after configuration.

What version of the product are you using? On what operating system?
Fedora 15 (2.6.40.4-5.fc15.i686.PAE)

Please provide any additional information below.

Debug log:
I | bootstrapper.py | MainThread | Line 88 | Mythbox Logger Initialized
D | platform.py | MainThread | Line 107 | syspath[0] = 
/home/zxarr/.xbmc/addons/script.mythbox
D | platform.py | MainThread | Line 107 | syspath[1] = 
/home/zxarr/.xbmc/addons/script.module.simplejson/lib
D | platform.py | MainThread | Line 107 | syspath[2] = 
/home/zxarr/.xbmc/addons/script.module.beautifulsoup/lib
D | platform.py | MainThread | Line 107 | syspath[3] = 
/usr/lib/xbmc/addons/script.module.pil/lib
D | platform.py | MainThread | Line 107 | syspath[4] = 
/home/zxarr/.xbmc/addons/script.module.elementtree/lib
D | platform.py | MainThread | Line 107 | syspath[5] = 
/usr/lib/xbmc/addons/script.module.pysqlite/lib
D | platform.py | MainThread | Line 107 | syspath[6] = /usr/lib/python27.zip
D | platform.py | MainThread | Line 107 | syspath[7] = /usr/lib/python2.7/
D | platform.py | MainThread | Line 107 | syspath[8] = 
/usr/lib/python2.7/plat-linux2
D | platform.py | MainThread | Line 107 | syspath[9] = /usr/lib/python2.7/lib-tk
D | platform.py | MainThread | Line 107 | syspath[10] = 
/usr/lib/python2.7/lib-old
D | platform.py | MainThread | Line 107 | syspath[11] = 
/usr/lib/python2.7/lib-dynload
D | platform.py | MainThread | Line 107 | syspath[12] = 
/home/zxarr/.xbmc/addons/script.mythbox/resources/src
D | platform.py | MainThread | Line 107 | syspath[13] = 
/home/zxarr/.xbmc/addons/script.mythbox/resources/lib/decorator
D | platform.py | MainThread | Line 107 | syspath[14] = 
/home/zxarr/.xbmc/addons/script.mythbox/resources/lib/odict
D | platform.py | MainThread | Line 107 | syspath[15] = 
/home/zxarr/.xbmc/addons/script.mythbox/resources/lib/bidict
D | platform.py | MainThread | Line 107 | syspath[16] = 
/home/zxarr/.xbmc/addons/script.mythbox/resources/lib/elementtree
D | platform.py | MainThread | Line 107 | syspath[17] = 
/home/zxarr/.xbmc/addons/script.mythbox/resources/lib/tvdb_api
D | platform.py | MainThread | Line 107 | syspath[18] = 
/home/zxarr/.xbmc/addons/script.mythbox/resources/lib/tvrage
D | platform.py | MainThread | Line 107 | syspath[19] = 
/home/zxarr/.xbmc/addons/script.mythbox/resources/lib/themoviedb
D | platform.py | MainThread | Line 107 | syspath[20] = 
/home/zxarr/.xbmc/addons/script.mythbox/resources/lib/IMDbPY
D | platform.py | MainThread | Line 107 | syspath[21] = 
/home/zxarr/.xbmc/addons/script.mythbox/resources/lib/simplejson
D | platform.py | MainThread | Line 107 | syspath[22] = 
/home/zxarr/.xbmc/addons/script.mythbox/resources/lib/mysql-connector-python
D | platform.py | MainThread | Line 107 | syspath[23] = 
/home/zxarr/.xbmc/addons/script.mythbox/resources/lib/python-twitter
D | platform.py | MainThread | Line 107 | syspath[24] = 
/home/zxarr/.xbmc/addons/script.mythbox/resources/lib/twisted
D | platform.py | MainThread | Line 107 | syspath[25] = 
/home/zxarr/.xbmc/addons/script.mythbox/resources/lib/zope.interface
D | platform.py | MainThread | Line 107 | syspath[26] = 
/home/zxarr/.xbmc/addons/script.mythbox/resources/lib/mockito
D | platform.py | MainThread | Line 107 | syspath[27] = 
/home/zxarr/.xbmc/addons/script.mythbox/resources/lib/unittest2
D | platform.py | MainThread | Line 107 | syspath[28] = 
/home/zxarr/.xbmc/addons/script.mythbox/resources/lib/unittest
D | platform.py | MainThread | Line 107 | syspath[29] = 
/home/zxarr/.xbmc/addons/script.mythbox/resources/test
I | bootstrapper.py | MainThread | Line 100 | MythBox 1.0.4 Initialized
D | settings.py | MainThread | Line 152 | Loading settings from 
/home/zxarr/.xbmc/userdata/addon_data/script.mythbox/settings.xml
D | bootstrapper.py | MainThread | Line 215 | Punting on debug shell -- not 
packaged
E | util.py | MainThread | Line 307 | (<type 'exceptions.AttributeError'>, 
AttributeError('onInit',), <traceback object at 0xabb1ed4c>)
E | util.py | MainThread | Line 308 | CATCHALL_UI: Caught <type 
'exceptions.AttributeError'> exception onInit on method onInit
Traceback (most recent call last):
  File "/home/zxarr/.xbmc/addons/script.mythbox/resources/src/mythbox/util.py", line 305, in catchall_ui
    return func(*args, **kw)
  File "/home/zxarr/.xbmc/addons/script.mythbox/resources/src/mythbox/ui/home.py", line 87, in onInit
    self.initCoverFlow()
  File "/home/zxarr/.xbmc/addons/script.mythbox/resources/src/mythbox/ui/home.py", line 95, in initCoverFlow
    for i in range(MAX_COVERFLOW):
  File "/home/zxarr/.xbmc/addons/script.mythbox/resources/src/mythbox/ui/home.py", line 61, in onFocus
    log.debug('lastfocusid = %s' % controlId)
  File "/usr/lib/python2.7/logging/__init__.py", line 1120, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1249, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/logging/__init__.py", line 1223, in makeRecord
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
  File "/usr/lib/python2.7/logging/__init__.py", line 284, in __init__
    self.threadName = threading.current_thread().name
  File "/usr/lib/python2.7/threading.py", line 806, in currentThread
    return _active[_get_ident()]
AttributeError: onInit
D | settings.py | MainThread | Line 182 | Saving settings to 
/home/zxarr/.xbmc/userdata/addon_data/script.mythbox/settings.xml
D | fanart.py | MainThread | Line 155 | Cache size google.pickle 0.00 KB
D | fanart.py | MainThread | Line 155 | Cache size imdb.pickle 0.00 KB
D | fanart.py | MainThread | Line 155 | Cache size imdb.pickle 0.00 KB
D | fanart.py | MainThread | Line 155 | Cache size tmdb.pickle 0.00 KB
D | fanart.py | MainThread | Line 155 | Cache size tmdb.pickle 0.00 KB
D | fanart.py | MainThread | Line 155 | Cache size tvdb.pickle 0.00 KB
D | fanart.py | MainThread | Line 155 | Cache size tvdb.pickle 0.00 KB
D | fanart.py | MainThread | Line 155 | Cache size tvrage.pickle 0.00 KB
D | fanart.py | MainThread | Line 155 | Cache size tvrage.pickle 0.00 KB
W | util.py | MainThread | Line 237 | TIMER: shutdown took 1.54 seconds
D | bus.py | MainThread | Line 58 | Publishing event {'id': 'SHUTDOWN'} to 5 
listeners
E | home.py | MainThread | Line 218 | shutting down publisher
Traceback (most recent call last):
  File "/home/zxarr/.xbmc/addons/script.mythbox/resources/src/mythbox/ui/home.py", line 216, in shutdown
    self.publisher.shutdown()
AttributeError: 'HomeWindow' object has no attribute 'publisher'
E | home.py | MainThread | Line 242 | Waiting for worker threads to die
Traceback (most recent call last):
  File "/home/zxarr/.xbmc/addons/script.mythbox/resources/src/mythbox/ui/home.py", line 237, in shutdown
    pool.pools['dbPool'].stopReaping = True
KeyError: 'dbPool'
I | home.py | MainThread | Line 255 | Goodbye!


```

Original issue reported on code.google.com by `Zixie...@gmail.com` on 23 Nov 2011 at 2:05

**Comment by GoogleCodeExporter** [comment]
```
I can't get it working via the RPMFusion install of XBMC. However, if I compile 
XBMC from source on Fedora 16, it works just fine.  Don't know why the 
rpmfusion version has such problems :-(

```

Original comment by `semir.pa...@gmail.com` on 24 Feb 2012 at 7:36
