### ISSUE TITLE
mysql dll not found on amd64 build

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/mythbox#2]
```
Hi,

I have setup the MythBox script as described in the readme. But I am not
getting the settings screen from point 5 of the instructions.

Whole setup:
- Mythbuntu 8.10 AMD64
- XBMC - SVN 16841
- MythTV - SVN trunk

mythbox.log:
DEBUG | __init__.py | Line 1072 | Mythbox Logger Initialized
ERROR | __init__.py | Line 1072 | Initializing stage 2
Traceback (most recent call last):
  File "/home/chronos/.xbmc/scripts/MythBox/default.py", line 137, in ?
    import mythtv
  File "/home/chronos/.xbmc/scripts/MythBox/resources/src/mythtv.py", line
23, in ?
    import mythdb
  File "/home/chronos/.xbmc/scripts/MythBox/resources/src/mythdb.py", line
22, in ?
    import MySQLdb
  File
"/home/chronos/.xbmc/scripts/MythBox/resources/lib/MySQLdb/MySQLdb/__init__.py",
line 19, in ?
    import _mysql
ImportError: unknown dlopen() error

Thanks in advance

Lars Schmohl

```

Original issue reported on code.google.com by `semir.pa...@gmail.com` on 10 Jan 2009 at 7:34

**Comment by GoogleCodeExporter** [comment]
```
I had this problem too and was able to work around by replacing the _mysql.so in
MythBox/resources/lib/MySQLdb/linux/_mysql.so with the one from my
python2.5/site-packages. After that I am stuck. Please let me know if you get 
further
```

Original comment by `mtuck...@gmail.com` on 11 Jan 2009 at 1:12

**Comment by GoogleCodeExporter** [comment]
```
Fixed in SVN 676 - Needs verification. Someone with 64bit please verify.
```

Original comment by `semir.pa...@gmail.com` on 11 Jan 2009 at 9:43
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `semir.pa...@gmail.com` on 8 Mar 2009 at 2:06
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
```
I'm using xbmc SVN 19630
mythbox SVN 865
mythtv 0.21 from fixes branch.
On Archlinux x86_64
mysql-python-1.2.3b2-1
libmysqlclient 5.1.34-1
Python 2.6.1

cat mythbox.log
DEBUG | __init__.py | Line 1072 | Mythbox Logger Initialized
ERROR | __init__.py | Line 1072 | Initializing stage 2
Traceback (most recent call last):
  File "/home/rich/.xbmc/scripts/MythBox/default.py", line 141, in ?
    import mythtv
  File "/home/rich/.xbmc/scripts/MythBox/resources/src/mythtv.py", line 22, in ?
    import mythdb
  File "/home/rich/.xbmc/scripts/MythBox/resources/src/mythdb.py", line 22, in ?
    import MySQLdb
  File "/home/rich/.xbmc/scripts/MythBox/resources/lib/MySQLdb/MySQLdb/__init__.py",
line 19, in ?
    import _mysql
ImportError: unknown dlopen() error

```

Original comment by `atkins...@gmail.com` on 23 Apr 2009 at 1:03

**Comment by GoogleCodeExporter** [comment]
```
atkinsonr, please attach your xbmc.log


```

Original comment by `semir.pa...@gmail.com` on 25 Apr 2009 at 4:43

**Comment by GoogleCodeExporter** [comment]
```
The fun starts on line 323:

http://pastebin.com/f59b18025

thanks very much!
```

Original comment by `atkins...@gmail.com` on 25 Apr 2009 at 6:49

**Comment by GoogleCodeExporter** [comment]
```
Was the xbmc.log useful? 

I'm happy to provide any further information that might assist with solving the 
issue.

A thought: Is it possible for mythbox to use a system provided MySQLdb instead 
of a
bundled one?

many thanks.
```

Original comment by `atkins...@gmail.com` on 30 Apr 2009 at 1:11

**Comment by GoogleCodeExporter** [comment]
```
Well, since my copy of _mysql.so obviously didn't work on your amd64 box, can 
you
just attach your version which works and I'll bundle that binary instead. 
```

Original comment by `semir.pa...@gmail.com` on 7 May 2009 at 3:44
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Hi there.
Sorry I thought I had this issue starred, not sure why I didn't get notified 
about
your update.

Attached is the _mysql.so from my AMD64 system.

thanks so much!
```

Original comment by `atkins...@gmail.com` on 16 May 2009 at 9:47

Attachments:
- [_mysql.so](https://storage.googleapis.com/google-code-attachments/mythbox/issue-2/comment-9/_mysql.so)

**Comment by GoogleCodeExporter** [comment]
```
Fixed in svn 1081
```

Original comment by `semir.pa...@gmail.com` on 18 May 2009 at 3:31
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
I just downloaded this today. This is my missing link in mediacenter land....

This isue is holding me back! ;-)

Traceback (most recent call last):
  File "/home/[USERNAME]/.xbmc/scripts/My Scripts/MythBox/default.py", line 149, in ?
    import mythtv
  File "/home/[USERNAME]/.xbmc/scripts/My Scripts/MythBox/resources/src/mythtv.py",
line 22, in ?
    import mythdb
  File "/home/[USERNAME]/.xbmc/scripts/My Scripts/MythBox/resources/src/mythdb.py",
line 22, in ?
    import MySQLdb
  File "/home/[USERNAME]/.xbmc/scripts/My
Scripts/MythBox/resources/lib/MySQLdb/MySQLdb/__init__.py", line 19, in ?
    import _mysql
ImportError: unknown dlopen() error

uname -a:
Linux mc-001 2.6.27-14-generic #1 SMP Wed Apr 15 19:29:46 UTC 2009 x86_64 
GNU/Linux
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=8.10
DISTRIB_CODENAME=intrepid
DISTRIB_DESCRIPTION="Ubuntu 8.10"

Thanks in advance,

I've tried linking MythBox/resources/lib/MySQLdb/linux64/_mysql.so to the 
python one
and i've tried copying the system one.

That results in crashes.
Thanks in advance!
```

Original comment by `wout.van...@gmail.com` on 1 Jun 2009 at 12:15

**Comment by GoogleCodeExporter** [comment]
```
I can confirm this issue it's not fixed. I've just tried with Beta 4 (SVN 1105)
version and results are the same described by wout.van.heeswijk (May 31, 2009) 
with
exactly the same log. I have also tried replacing
MythBox/resources/lib/MySQLdb/linux64/_mysql.so with
MythBox/resources/lib/MySQLdb/linux64/_mysql.so, and crashed after calling the 
script:

mythtv@linuxhost:~$ xbmc
/usr/share/xbmc/xbmc.bin: symbol lookup error:
/home/guindous/.xbmc/scripts/MythBox/resources/lib/MySQLdb/linux64/_mysql.so:
undefined symbol: Py_InitModule4_64

My XBMC-MythTV system is:
- Ubuntu Jaunty 9.04 (x64 version)
- XBMC 9.04.1
- Python 2.6 / python-mysqldb 1.2.2-7ubuntu1

If you need more information about it, i will be happy helping you and testing
mythbox on my amd64 box.

Thanks in advance,

--
elSeba



```

Original comment by `scarde...@gmail.com` on 8 Jun 2009 at 1:05

**Comment by GoogleCodeExporter** [comment]
```
I can also confirm the not-fixed-yet state as described by scardello and
wout.van.heeswijk. XBMC returns the ' unknown dlopen() error'; and after 
replacing
the _mysql.so in mythbox with the version from Ubuntu, it crashes with exactly 
the
same message als scardello posted in #12 (so it is reproducable). Possibly, 
however,
it's not made to work with the Ubuntu version of _mysql.so.
```

Original comment by `tobiaso...@gmail.com` on 14 Jun 2009 at 8:37

**Comment by GoogleCodeExporter** [comment]
```
I followed scardello's comments in #12 and have the exact same error.  This 
issue is
not yet fixed.

I, too, am running
* Ubuntu Jaunty 9.04 (x64)
* XBMC 9.04.2+svn20937
* mythbox-svn-1105.tar.gz 
* Python 2.6 / python-mysqldb 1.2.2-7ubuntu1
```

Original comment by `jjtay...@cise.ufl.edu` on 15 Jun 2009 at 9:28

**Comment by GoogleCodeExporter** [comment]
```
This might be of some help:

"Typically this means that an extension was compiled against the wrong Python.h.

This just means that the calling Python interpreter and the extension don't use 
the
same version (one is Python 2.4, the other 2.5). They were both 64-bit but the 
name
changed in http://www.python.org/dev/peps/pep-0353/

Some commands to help debug this are ldd (to show dymanic library linking) and 
nm (to
list exports)."

http://timhatch.com/ark/2008/08/07/py_initmodule4_64
```

Original comment by `jjtay...@cise.ufl.edu` on 15 Jun 2009 at 9:40

**Comment by GoogleCodeExporter** [comment]
```
Just confirmed our suspicions by installing your script on an x86 machine.  It 
works
fine on that box, but still does not work on the AMD64 box.
```

Original comment by `jjtay...@cise.ufl.edu` on 16 Jun 2009 at 11:34

**Comment by GoogleCodeExporter** [comment]
```
I am also having this problem. If there is anything that someone that knows very
little can do to help please let me know.
```

Original comment by `caleb.re...@gmail.com` on 22 Jun 2009 at 9:27

**Comment by GoogleCodeExporter** [comment]
```
hello,
i have the same probleme...
xbmcbuntu : ubuntu9.04 amd64
an issu ?
thanks
```

Original comment by `alain.ts...@gmail.com` on 29 Jun 2009 at 8:34

**Comment by GoogleCodeExporter** [comment]
```
I can also confirm that this is still an issue in svn 1105 on Ubuntu Jaunty 
9.04.

I found a working _mysql.so in python-mysqldb for intrepid.
Download the python-mysqldb deb from
http://packages.ubuntu.com/intrepid/python-mysqldb and put
usr/lib/python-support/python-mysqldb/python2.4/_mysql.so in
/MythBox/resources/lib/MySQLdb/linux64
```

Original comment by `anders.e...@gmail.com` on 11 Jul 2009 at 8:08

**Comment by GoogleCodeExporter** [comment]
```
Doing what anders.ejdeling said in comment 19 worked for me. Thanks!
```

Original comment by `caleb.re...@gmail.com` on 11 Jul 2009 at 8:29

**Comment by GoogleCodeExporter** [comment]
```
Same here, Jaunty 9.04 amd64.  The intrepid _mysql.so helps things.
```

Original comment by `arbran...@gmail.com` on 30 Jul 2009 at 2:29

**Comment by GoogleCodeExporter** [comment]
```
I am on Ubuntu 9.04 AMD64 and the script errors as well. I tried copying the
_mysql.so file from /usr/lib/python-support/python-mysqldb/python2.6 and
/usr/lib/python-support/python-mysqldb/python2.5 (I do not have 2.4) and now 
xbmc
crashes at 'importing mythtv' without error.

On my i386 Ubuntu everything seems to work fine, until I actually play a 
recording,
then I get the error Exception: (-5, 'No address associated with hostname') 
Function:
<function onInit at 0xa40c394c>.

The internal mythtv:// isn't working, i can't play via upnp or get this script 
to
work on amd64 or i386, so this is a big blocker for me.
```

Original comment by `birbeck` on 16 Aug 2009 at 3:40

**Comment by GoogleCodeExporter** [comment]
```
Re-opening. Working on a solution that will use your distribution's python 
bindings
and shared lib instead of me having to bundle a version to work with all 
possible
permutations:
- 32 bit vs 64bit
- python 2.4 vs 2.5 vs 2.6
- mysql client 5.0 vs 5.1

Please add a comment to this issue with your email address if you are willing 
to test
and provide feedback and I'll send out a version when it is ready. 
```

Original comment by `semir.pa...@gmail.com` on 19 Aug 2009 at 6:13
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Issue 48 has been merged into this issue.
```

Original comment by `semir.pa...@gmail.com` on 28 Aug 2009 at 9:56

**Comment by GoogleCodeExporter** [comment]
```
Issue 47 has been merged into this issue.
```

Original comment by `semir.pa...@gmail.com` on 28 Aug 2009 at 9:59

**Comment by GoogleCodeExporter** [comment]
```
Willing to test. Thanks for your efforts.
```

Original comment by `earlne...@gmail.com` on 8 Sep 2009 at 4:16

**Comment by GoogleCodeExporter** [comment]
```
also willing to test. I'm happy to make reports in the same style as my previous
reports if that helps. Send me an email.
```

Original comment by `beatbrea...@gmail.com` on 8 Sep 2009 at 6:56

**Comment by GoogleCodeExporter** [comment]
```
earlne & beatbreaker: email addys plz
```

Original comment by `semir.pa...@gmail.com` on 9 Sep 2009 at 11:45

**Comment by GoogleCodeExporter** [comment]
```
sorry i thought it came up - beatbreaker82@gmail.com
```

Original comment by `beatbrea...@gmail.com` on 11 Sep 2009 at 5:09

**Comment by GoogleCodeExporter** [comment]
```
If testing on ubuntu is needed: henry78@gmx.at
```

Original comment by `HenrySev...@gmail.com` on 1 Oct 2009 at 10:51

**Comment by GoogleCodeExporter** [comment]
```
I'm on a 64-bit machine (Gentoo, Python2.6) using mythbox-svn-1260. After 
installing
the script for the first time I received a dlopen() error. I attempted to use an
external copy _mysql.so as described here:
http://blog.xbmc.org/forum/showpost.php?p=384841&postcount=164

To no surprise that resulted in a crash.

I've attached the log file.

```

Original comment by `wes...@gmail.com` on 12 Oct 2009 at 4:46

Attachments:
- [mythbox.log](https://storage.googleapis.com/google-code-attachments/mythbox/issue-2/comment-31/mythbox.log)

**Comment by GoogleCodeExporter** [comment]
```
Just thought I'd comment that I'm seeing the same issue on 64-bit Ubuntu 9.04 
and am also willing to test a fix.
```

Original comment by `minne...@gmail.com` on 13 Oct 2009 at 10:40

**Comment by GoogleCodeExporter** [comment]
```
Fixed in svn 1510
```

Original comment by `semir.pa...@gmail.com` on 17 Oct 2009 at 5:43
- Changed state: **Fixed**
- Added labels: **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
Issue 62 has been merged into this issue.
```

Original comment by `semir.pa...@gmail.com` on 19 Oct 2009 at 6:01

**Comment by GoogleCodeExporter** [comment]
```
I can confirm this is fixed on amd64 using svn 1558. 

Thanks and keep up the good work!
```

Original comment by `wes...@gmail.com` on 29 Oct 2009 at 3:55
