### ISSUE TITLE
'NoneType' object ha no attribute 'ipAddress'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/mythbox#200]
```
What steps will reproduce the problem?
1. compile xbmc from source
2. add mythbox addon
3. start mythbox

What is the expected output? What do you see instead?
Errot:onInit
'NoneType' object ha no attribute 'ipAddress with a Ok button.

When pressing test settings under settings menu nothing happends.

What version of the product are you using? On what operating system?
Starting XBMC (11.0-PRE Git:20120217-f6c6361), Platform: Linux (Ubuntu 10.10, 
2.6.35-28-generic-pae i686). Built on Feb 18 2012

mythbox 1.1.0

Please provide any additional information below.

Enable mythbox logging, no log file is created.

xbmc.log
21:22:14 T:2794543984   ERROR: util.py:268 | MainThread | CATCHALL_UI: Caught 
<type 'exceptions.AttributeError'> exception 'NoneType' object has no attribute 
'ipAddress' on method onInit
                                            Traceback (most recent call last):
                                              File "/home/myth_vrum/.xbmc/addons/script.mythbox/resources/src/mythbox/util.py", line 265, in catchall_ui
                                                return func(*args, **kw)
                                              File "/home/myth_vrum/.xbmc/addons/script.mythbox/resources/src/mythbox/ui/home.py", line 88, in onInit
                                                self.startup()
                                              File "<string>", line 1, in <lambda>
                                              File "/home/myth_vrum/.xbmc/addons/script.mythbox/resources/src/mythbox/ui/toolkit.py", line 199, in window_busy
                                                result = func(*args, **kwargs)
                                              File "/home/myth_vrum/.xbmc/addons/script.mythbox/resources/src/mythbox/ui/home.py", line 164, in startup
                                                self.settings.verify()
                                              File "/home/myth_vrum/.xbmc/addons/script.mythbox/resources/src/mythbox/settings.py", line 203, in verify
                                                self.verifyMythTVConnectivity()
                                              File "/home/myth_vrum/.xbmc/addons/script.mythbox/resources/src/mythbox/settings.py", line 223, in verifyMythTVConnectivity
                                                raise SettingsException('Connection to MythTV host %s failed: %s' % (db.getMasterBackend().ipAddress, ex))
                                            AttributeError: 'NoneType' object has no attribute 'ipAddress'
*****
In mythbackend.log no access attempt can bee seen, 
In xbmc myth:// can be used to watch LiveTv

```

Original issue reported on code.google.com by `ulbj125...@gmail.com` on 20 Feb 2012 at 8:45

**Comment by GoogleCodeExporter** [comment]
```
I can't tell which what version your backend is from what you've provided.  
attaching your log may help
```

Original comment by `semir.pa...@gmail.com` on 21 Feb 2012 at 12:22

**Comment by GoogleCodeExporter** [comment]
```
Which backend? Xbmc or myth?
```

Original comment by `ulbj125...@gmail.com` on 21 Feb 2012 at 9:52

**Comment by GoogleCodeExporter** [comment]
```
snippet from mythtv backend log:
2012-02-16 22:00:58.800 mythbackend version: tags/release-0-24 [exporterad] 
www.mythtv.org

2012-02-16 22:00:58.885 Current MythTV Schema Version (DBSchemaVer): 1264


```

Original comment by `ulbj125...@gmail.com` on 22 Feb 2012 at 6:34

**Comment by GoogleCodeExporter** [comment]
```
Looks like the sql query to determine the master backend is not returning any 
rows. This is the first time this has been reported as a problem.  Have you 
hand edited any of the data in the "settings" table?  Try running this query 
and see if it returns any data. If not, attach a dump of your settings table 
and I might be able to take a look.

select 
                    a.data as ipaddr,
                    b.data as port,
                    c.hostname as hostname
                from 
                    settings a, 
                    settings b,
                    settings c
                where 
                    a.value = 'MasterServerIP' and
                    b.value = 'MasterServerPort' and
                    c.value = 'BackendServerIP' and
                    c.data  = a.data
```

Original comment by `semir.pa...@gmail.com` on 24 Feb 2012 at 7:22

**Comment by GoogleCodeExporter** [comment]
```
MasterServerPort was set to 127.0.0.1, when I changed MasterServerPort actual 
ip of host, it started to work. Even if mythbackend and xbmc with Mythbox was 
running on the same machine. 

Do I need to take any action to close TR?

Thx for support. 

Best regards
```

Original comment by `ulbj125...@gmail.com` on 24 Feb 2012 at 5:28

**Comment by GoogleCodeExporter** [comment]
```
enjoy!
```

Original comment by `semir.pa...@gmail.com` on 24 Feb 2012 at 6:36
- Changed state: **Invalid**
