### ISSUE TITLE
Connection to MythTV host failed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/mythbox#202]
```
What steps will reproduce the problem?
1. Install mythtv-0.25.0-20120223 (Using protocol version 72)
2. Try to connect with mythbox 1.1.0

What is the expected output? What do you see instead?
mythbox jumping directly to its settings-screen

What version of the product are you using? On what operating system?
Backend OS Ubuntu 12.04-alpha with 0.25.0~master.20120223.532cee8-0ubuntu1
mythbox 1.1.0 on openELEC-devel-snapshot

Please provide any additional information below.

from xbmc.log:

17:38:26 T:2825911152  NOTICE: -->Python Interpreter Initialized<--
17:38:26 T:2825911152  NOTICE: MythBox for XBMC
17:38:26 T:2825911152  NOTICE: MythBox: loggerIniFile = 
/storage/.xbmc/addons/script.mythbox/mythbox_log.ini
17:38:28 T:2825911152   ERROR: settings.py:222 | MainThread | Unsupported 
protocol: 72
                                            Traceback (most recent call last):
                                              File "/storage/.xbmc/addons/script.mythbox/resources/src/mythbox/settings.py", line 219, in verifyMythTVConnectivity
                                                session = Connection(self, translator=self.translator, platform=self.platform, bus=EventBus(), db=db)
                                              File "/storage/.xbmc/addons/script.mythbox/resources/src/mythbox/mythtv/conn.py", line 207, in __init__
                                                self.db_init()
                                              File "<string>", line 1, in <lambda>
                                              File "/storage/.xbmc/addons/script.mythbox/resources/src/mythbox/mythtv/db.py", line 87, in inject_db
                                                return func(*args, **kwargs)
                                              File "/storage/.xbmc/addons/script.mythbox/resources/src/mythbox/mythtv/conn.py", line 215, in db_init
                                                self.cmdSock = self.connect()
                                              File "<string>", line 1, in <lambda>
                                              File "/storage/.xbmc/addons/script.mythbox/resources/src/mythbox/mythtv/db.py", line 87, in inject_db
                                                return func(*args, **kwargs)
                                              File "/storage/.xbmc/addons/script.mythbox/resources/src/mythbox/mythtv/conn.py", line 242, in connect
                                                raise ProtocolException('Unsupported protocol: %s' % protocol.serverVersion)
                                            ProtocolException: Unsupported protocol: 72

```

Original issue reported on code.google.com by `stefan.l...@googlemail.com` on 29 Feb 2012 at 4:50

**Comment by GoogleCodeExporter** [comment]
```
i'm affected with the same issue no connection to mythtv 0.25 in pangolin
```

Original comment by `mig...@gmail.com` on 13 Mar 2012 at 11:19

**Comment by GoogleCodeExporter** [comment]
```
I get the same. Using Ubuntu Desktop 12.04 Beta 2 with XBMC from 
http://ppa.launchpad.net/nathan-renniewaldock/xbmc-stable/ubuntu precise
```

Original comment by `thehouse...@gmail.com` on 2 Apr 2012 at 12:03

**Comment by GoogleCodeExporter** [comment]
```
Sorry, I should have mentioned I realise the problem in that MythTV 2.5 isn't 
supported yet by MythBox. Just my 2 cents worth to request support for MythTV 
2.5 since that is the version in the very soon to be released Ubuntu LTS. 
Thanks!
```

Original comment by `thehouse...@gmail.com` on 2 Apr 2012 at 12:55

**Comment by GoogleCodeExporter** [comment]
```
Samething here. Just upgraded MythTV to 0.25 and I get the Unsupported Protocol 
error as well.
```

Original comment by `srunner2...@gmail.com` on 12 Apr 2012 at 2:44

**Comment by GoogleCodeExporter** [comment]
```
Bump Can we get this looked at?
```

Original comment by `Forrest....@gmail.com` on 17 Apr 2012 at 4:40

**Comment by GoogleCodeExporter** [comment]
```
will not connect
```

Original comment by `rcl...@gmail.com` on 9 May 2012 at 6:36

**Comment by GoogleCodeExporter** [comment]
```
Same issue here. MythTV 0.25 and latest MythBox. Any love on getting mythbox 
functional with current MythTV?
```

Original comment by `erich.ne...@gmail.com` on 3 Jun 2012 at 5:46

**Comment by GoogleCodeExporter** [comment]
```
Hi all,
Install the latest one from downloads, it works for me: script.mythbox.1.1.0.zip
Download it and install it "from zip" in XBMC.
No more protocol-issues in 0.25. However, it seems that viewing recordings is 
limited to a maximum of 5, - but then again it might be a question of 
configuration.
Hope this helps you!

Best regards,
Dan
```

Original comment by `eckbergc...@gmail.com` on 3 Jun 2012 at 11:33

**Comment by GoogleCodeExporter** [comment]
```
Well, 1.1.0 supports protocol versions up to 70. My mythtv-0.25-fixes uses 
protocol version 72.

Are you sure this works? Which protocol version does your 0.25 use?
```

Original comment by `stefan.l...@googlemail.com` on 3 Jun 2012 at 11:47

**Comment by GoogleCodeExporter** [comment]
```
No, I'm sorry I was a bit too fast with the version-number. Its actually 1.1.1 
that works for me.

This is from the changelog of 1.1.1:
x/x/2011 - MythBox 1.1.1
-----------------------------

  New
    - Protocol 71 and 72 support (Sebastian Astie)

  Fixed
    - Don't redraw the channel column when scrolling left or right in 
      the TV Guide
    - MythTV 0.21 backwards compatibility (Robert Klep)
    - Programs from 'Deleted' storage group removed from current
      recordings (Robert Klep)

```

Original comment by `eckbergc...@gmail.com` on 3 Jun 2012 at 1:39

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the comment...but where do I find version 1.1.1? The latest listed 
in the downloads is 1.1.0.
```

Original comment by `erich.ne...@gmail.com` on 3 Jun 2012 at 11:00

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I believe I got it from git back in march or something like that.
This of course is not optimal since its not a "release", on the other hand, 
with the current release of mythbox, you're forced to stay at MythTV 0.24 or 
hacking the protocol-check in python.

If you do a "git clone git://github.com/analogue/mythbox.git" you'll get a 
version with support for 0.72. As mentioned not optimal, but you'll be able to 
use MythTV 0.25. You can just backup your original mythbox-dir and then 
overwrite with the git-cloned version to see how it goes.

Its not a solution, its a workaround, i know ;) but hopefully it'll give some 
sort of comfort to the people on this list.
```

Original comment by `eckbergc...@gmail.com` on 4 Jun 2012 at 9:00

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Thanks for your advice. Tried the git version, and it successfully connects to 
the mysql-database on my backend.

But sadly I'm not able to play anything. I am able to browse the recordings 
list and can see the tv-guide, but when I try to watch something nothing 
happens. Instead I'm getting errors in xbmc.log:

16:23:59 T:3016951552  NOTICE: DVDPlayer: Opening: 
myth://mythtv:mypass@192.168.0.99:6543/channels/5.ts
16:23:59 T:3016951552 WARNING: CDVDMessageQueue(player)::Put 
MSGQ_NOT_INITIALIZED
16:23:59 T:2995776320  NOTICE: Thread CDVDPlayer start, auto delete: false
16:23:59 T:2995776320  NOTICE: Creating InputStream
16:23:59 T:2995776320   ERROR: GetControl - unable to connect to server on 
192.168.0.99:6543
16:23:59 T:2995776320   ERROR: CDVDPlayer::OpenInputStream - error opening 
[myth://mythtv:mypass@192.168.0.99:6543/channels/5.ts]
16:23:59 T:2995776320  NOTICE: CDVDPlayer::OnExit()
16:23:59 T:2995776320  NOTICE: CDVDPlayer::OnExit() deleting input stream
16:24:00 T:3016951552  NOTICE: CDVDPlayer::CloseFile()
16:24:00 T:3016951552 WARNING: CDVDMessageQueue(player)::Put 
MSGQ_NOT_INITIALIZED
16:24:00 T:3016951552  NOTICE: DVDPlayer: waiting for threads to exit
16:24:00 T:3016951552  NOTICE: DVDPlayer: finished waiting

Cannot say at this time, what's the problem here. Other frontends (e.g. my 
notebook) with mythfrontend as a client work flawlessly. Maybe it's a 
backend-problem, maybe it's my openelec-client ... maybe I should be patient 
until the next official release is published. ;)

```

Original comment by `stefan.l...@googlemail.com` on 4 Jun 2012 at 2:36

**Comment by GoogleCodeExporter** [comment]
```
Comment 15 by stefan.l...@gmail.com, Jun 4, 2012 

I have the exact same issue. I can see the records but play nothing. Even the 
ineteral myth:// in xbmc will not connect to the mythbackend :(
```

Original comment by `the...@gmail.com` on 3 Aug 2012 at 8:15

**Comment by GoogleCodeExporter** [comment]
```
same issue with xmbc 11 and myth .26
```

Original comment by `henkem...@gmail.com` on 3 Dec 2012 at 1:41
