### ISSUE TITLE
Does not connect to MythTV .25 DB

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/mythbox#211]
```
What steps will reproduce the problem?
1. Have a mythtv backend running .25
2. Try to connect to it via Mythbox
3. See error message after Test Settings. Only the first three letters of the 
error message are visible in dialog box

What is the expected output? What do you see instead?
I am aware that Mythbox says it supports .24, however I needed to upgrade to 
.25. I was expecting it to connect to the db. It says cannot connect.

What version of the product are you using? On what operating system?
XBMC 11.0 and the version of mythbox that gets added in a fresh install

Please provide any additional information below.

xbmc.log

19:42:10 T:3672  NOTICE: 
-----------------------------------------------------------------------
19:42:10 T:3672  NOTICE: Starting XBMC (11.0 Git:20120321-14feb09), Platform: 
Windows 7, 64-bit (WoW) Service Pack 1 build 7601. Built on Mar 21 2012 
(compiler 1600)
19:42:10 T:3672  NOTICE: AMD Athlon(tm) 64 Processor 3200+
19:42:10 T:3672  NOTICE: Desktop Resolution: 1360x768 32Bit at 60Hz
19:42:10 T:3672  NOTICE: Running with administrator rights
19:42:10 T:3672  NOTICE: Aero is enabled
19:42:10 T:3672  NOTICE: special://xbmc/ is mapped to: C:\Program Files 
(x86)\XBMC
19:42:10 T:3672  NOTICE: special://xbmcbin/ is mapped to: C:\Program Files 
(x86)\XBMC
19:42:10 T:3672  NOTICE: special://masterprofile/ is mapped to: 
C:\Users\cpadmin\AppData\Roaming\XBMC\userdata
19:42:10 T:3672  NOTICE: special://home/ is mapped to: 
C:\Users\cpadmin\AppData\Roaming\XBMC\
19:42:10 T:3672  NOTICE: special://temp/ is mapped to: 
C:\Users\cpadmin\AppData\Roaming\XBMC\cache
19:42:10 T:3672  NOTICE: The executable running is: C:\Program Files 
(x86)\XBMC\XBMC.exe
19:42:10 T:3672  NOTICE: Local hostname: hp64
19:42:10 T:3672  NOTICE: Log File is located: 
C:\Users\cpadmin\AppData\Roaming\XBMC\xbmc.log
19:42:10 T:3672  NOTICE: 
-----------------------------------------------------------------------
19:42:10 T:3672  NOTICE: Setup SDL
19:42:10 T:3672  NOTICE: Found screen: Generic PnP Monitor on ATI Radeon HD 
3400 Series, adapter 0.
19:42:10 T:3672  NOTICE: Primary mode: 1360x768 @ 60.00 - Full Screen
19:42:10 T:3672  NOTICE: Additional mode: 640x480 @ 59.94 - Full Screen
19:42:10 T:3672  NOTICE: Additional mode: 640x480 @ 60.00 - Full Screen
19:42:10 T:3672  NOTICE: Additional mode: 640x480 @ 73.00 - Full Screen
19:42:10 T:3672  NOTICE: Additional mode: 640x480 @ 75.00 - Full Screen
19:42:10 T:3672  NOTICE: Additional mode: 720x480 @ 60.00 - Full Screen
19:42:10 T:3672  NOTICE: Additional mode: 720x480 @ 75.00 - Full Screen
19:42:10 T:3672  NOTICE: Additional mode: 800x600 @ 60.00 - Full Screen
19:42:10 T:3672  NOTICE: Additional mode: 800x600 @ 70.00 - Full Screen
19:42:10 T:3672  NOTICE: Additional mode: 800x600 @ 72.00 - Full Screen
19:42:10 T:3672  NOTICE: Additional mode: 800x600 @ 75.00 - Full Screen
19:42:10 T:3672  NOTICE: Additional mode: 848x480 @ 60.00 - Full Screen
19:42:10 T:3672  NOTICE: Additional mode: 848x480 @ 75.00 - Full Screen
19:42:10 T:3672  NOTICE: Additional mode: 1024x768 @ 60.00 - Full Screen
19:42:10 T:3672  NOTICE: Additional mode: 1024x768 @ 70.00 - Full Screen
19:42:10 T:3672  NOTICE: Additional mode: 1024x768 @ 72.00 - Full Screen
19:42:10 T:3672  NOTICE: Additional mode: 1024x768 @ 75.00 - Full Screen
19:42:10 T:3672  NOTICE: Additional mode: 1280x720 @ 60.00 - Full Screen
19:42:10 T:3672  NOTICE: Additional mode: 1360x768 @ 60.00 - Full Screen
19:42:10 T:3672  NOTICE: load settings...
19:42:10 T:3672  NOTICE: special://profile/ is mapped to: 
special://masterprofile/
19:42:10 T:3672  NOTICE: loading special://masterprofile/guisettings.xml
19:42:10 T:3672   ERROR: special://masterprofile/guisettings.xml, Line 0
                                            Failed to open file
19:42:10 T:3672   ERROR: Unable to load 
special://masterprofile/guisettings.xml, creating new 
special://masterprofile/guisettings.xml with default values
19:42:10 T:3672  NOTICE: Getting hardware information now...
19:42:10 T:3672  NOTICE: Checking resolution 12
19:42:10 T:3672  NOTICE: Loading player core factory settings from 
special://xbmc/system/playercorefactory.xml.
19:42:10 T:3672  NOTICE: Loaded playercorefactory configuration
19:42:10 T:3672  NOTICE: Loading player core factory settings from 
special://masterprofile/playercorefactory.xml.
19:42:10 T:3672  NOTICE: special://masterprofile/playercorefactory.xml does not 
exist. Skipping.
19:42:10 T:3672  NOTICE: No settings file to load 
(special://xbmc/system/advancedsettings.xml)
19:42:10 T:3672  NOTICE: No settings file to load 
(special://masterprofile/advancedsettings.xml)
19:42:10 T:3672  NOTICE: Default DVD Player: dvdplayer
19:42:10 T:3672  NOTICE: Default Video Player: dvdplayer
19:42:10 T:3672  NOTICE: Default Audio Player: paplayer
19:42:10 T:3672  NOTICE: Disabled debug logging due to GUI setting. Level 0.
19:42:10 T:3672  NOTICE: Log level changed to 0
19:42:10 T:3672  NOTICE: Loading media sources from 
special://masterprofile/sources.xml
19:42:12 T:3672  NOTICE: initializing playlistplayer
19:42:12 T:3672  NOTICE: DONE initializing playlistplayer
19:42:14 T:3672  NOTICE: initialize done
19:42:14 T:3672  NOTICE: Running the application...
19:42:14 T:3672  NOTICE: ES: Starting event server
19:42:14 T:2164  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
19:42:14 T:2164  NOTICE: UDP: Listening on port 9777
19:42:14 T:2960   ERROR: CRemoteControl::Connect - failed to connect
19:42:15 T:2916  NOTICE: -->Python Interpreter Initialized<--
19:43:01 T:2368 WARNING: XFILE::CFactoryDirectory::Create - Unsupported 
protocol(script) in script://
19:44:14 T:1504  NOTICE: VideoInfoScanner: Starting scan ..
19:44:18 T:3552 WARNING: XFILE::CFactoryDirectory::Create - Unsupported 
protocol(script) in script://
19:44:19 T:2744  NOTICE: -->Python Interpreter Initialized<--
19:44:19 T:2744  NOTICE: MythBox for XBMC
19:44:19 T:2744  NOTICE: MythBox: loggerIniFile = 
C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\mythbox_log.ini
19:44:22 T:2744   ERROR: 
C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbo
x\ui\toolkit.py:273: DeprecationWarning: object.__init__() takes no parameters
                                              xbmcgui.WindowXML.__init__(self, *args, **kwargs)
19:44:23 T:2532 WARNING: XFILE::CFactoryDirectory::Create - Unsupported 
protocol(script) in script://
19:45:31 T:1504   ERROR: ADDON::CScraper::Run: Unable to parse web site
19:45:51 T:2744   ERROR: settings.py:222 | MainThread | Unsupported protocol: 72
                                            Traceback (most recent call last):
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\settings.py", line 219, in verifyMythTVConnectivity
                                                session = Connection(self, translator=self.translator, platform=self.platform, bus=EventBus(), db=db)
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\mythtv\conn.py", line 207, in __init__
                                                self.db_init()
                                              File "<string>", line 1, in <lambda>
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\mythtv\db.py", line 87, in inject_db
                                                return func(*args, **kwargs)
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\mythtv\conn.py", line 215, in db_init
                                                self.cmdSock = self.connect()
                                              File "<string>", line 1, in <lambda>
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\mythtv\db.py", line 87, in inject_db
                                                return func(*args, **kwargs)
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\mythtv\conn.py", line 242, in connect
                                                raise ProtocolException('Unsupported protocol: %s' % protocol.serverVersion)
                                            ProtocolException: Unsupported protocol: 72
19:46:37 T:1504   ERROR: Previous line repeats 1 times.
19:46:37 T:1504   ERROR: ADDON::CScraper::Run: Unable to parse web site
19:48:04 T:2744   ERROR: Previous line repeats 9 times.
19:48:04 T:2744   ERROR: settings.py:222 | MainThread | Unsupported protocol: 72
                                            Traceback (most recent call last):
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\settings.py", line 219, in verifyMythTVConnectivity
                                                session = Connection(self, translator=self.translator, platform=self.platform, bus=EventBus(), db=db)
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\mythtv\conn.py", line 207, in __init__
                                                self.db_init()
                                              File "<string>", line 1, in <lambda>
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\mythtv\db.py", line 87, in inject_db
                                                return func(*args, **kwargs)
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\mythtv\conn.py", line 215, in db_init
                                                self.cmdSock = self.connect()
                                              File "<string>", line 1, in <lambda>
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\mythtv\db.py", line 87, in inject_db
                                                return func(*args, **kwargs)
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\mythtv\conn.py", line 242, in connect
                                                raise ProtocolException('Unsupported protocol: %s' % protocol.serverVersion)
                                            ProtocolException: Unsupported protocol: 72
19:48:26 T:2744   ERROR: toolkit.py:129 | MainThread | validator
                                            Traceback (most recent call last):
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\ui\toolkit.py", line 125, in enterText
                                                validator(txt)
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\ui\uisettings.py", line 67, in validate
                                                raise SettingsException(str(ex))
                                            SettingsException: Recording directory 't:\' does not exist.
19:48:53 T:2744   ERROR: toolkit.py:129 | MainThread | validator
                                            Traceback (most recent call last):
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\ui\toolkit.py", line 125, in enterText
                                                validator(txt)
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\ui\uisettings.py", line 67, in validate
                                                raise SettingsException(str(ex))
                                            SettingsException: Recording directory 'T:\' does not exist.
19:48:53 T:1504   ERROR: ADDON::CScraper::Run: Unable to parse web site
19:49:01 T:2744   ERROR: toolkit.py:129 | MainThread | validator
                                            Traceback (most recent call last):
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\ui\toolkit.py", line 125, in enterText
                                                validator(txt)
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\ui\uisettings.py", line 67, in validate
                                                raise SettingsException(str(ex))
                                            SettingsException: Recording directory 'T:\' does not exist.
19:49:09 T:2744   ERROR: toolkit.py:129 | MainThread | validator
                                            Traceback (most recent call last):
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\ui\toolkit.py", line 125, in enterText
                                                validator(txt)
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\ui\uisettings.py", line 67, in validate
                                                raise SettingsException(str(ex))
                                            SettingsException: Recording directory 'T:/' does not exist.
19:49:35 T:1504   ERROR: ADDON::CScraper::Run: Unable to parse web site
19:49:43 T:2744   ERROR: settings.py:222 | MainThread | Unsupported protocol: 72
                                            Traceback (most recent call last):
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\settings.py", line 219, in verifyMythTVConnectivity
                                                session = Connection(self, translator=self.translator, platform=self.platform, bus=EventBus(), db=db)
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\mythtv\conn.py", line 207, in __init__
                                                self.db_init()
                                              File "<string>", line 1, in <lambda>
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\mythtv\db.py", line 87, in inject_db
                                                return func(*args, **kwargs)
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\mythtv\conn.py", line 215, in db_init
                                                self.cmdSock = self.connect()
                                              File "<string>", line 1, in <lambda>
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\mythtv\db.py", line 87, in inject_db
                                                return func(*args, **kwargs)
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\mythtv\conn.py", line 242, in connect
                                                raise ProtocolException('Unsupported protocol: %s' % protocol.serverVersion)
                                            ProtocolException: Unsupported protocol: 72
19:50:31 T:3672   ERROR: Control 250 in window 13001 has been asked to focus, 
but it can't
19:50:32 T:3672   ERROR: CLocalizeStrings::ClearBlock: Trying to clear non 
existent block C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox
19:50:32 T:2744   ERROR: settings.py:222 | MainThread | Unsupported protocol: 72
                                            Traceback (most recent call last):
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\settings.py", line 219, in verifyMythTVConnectivity
                                                session = Connection(self, translator=self.translator, platform=self.platform, bus=EventBus(), db=db)
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\mythtv\conn.py", line 207, in __init__
                                                self.db_init()
                                              File "<string>", line 1, in <lambda>
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\mythtv\db.py", line 87, in inject_db
                                                return func(*args, **kwargs)
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\mythtv\conn.py", line 215, in db_init
                                                self.cmdSock = self.connect()
                                              File "<string>", line 1, in <lambda>
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\mythtv\db.py", line 87, in inject_db
                                                return func(*args, **kwargs)
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\mythtv\conn.py", line 242, in connect
                                                raise ProtocolException('Unsupported protocol: %s' % protocol.serverVersion)
                                            ProtocolException: Unsupported protocol: 72
19:50:32 T:2744  NOTICE: Before fanart shutdown
19:50:33 T:3672   ERROR: Control 250 in window 13001 has been asked to focus, 
but it can't
19:50:35 T:2744  NOTICE: Before bus.publish
19:50:35 T:2744   ERROR: home.py:221 | MainThread | shutting down publisher
                                            Traceback (most recent call last):
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\ui\home.py", line 219, in shutdown
                                                self.publisher.shutdown()
                                            AttributeError: 'HomeWindow' object has no attribute 'publisher'
19:50:35 T:2744  NOTICE: Before reaping
19:50:35 T:2744   ERROR: home.py:245 | MainThread | Waiting for worker threads 
to die
                                            Traceback (most recent call last):
                                              File "C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox\resources\src\mythbox\ui\home.py", line 240, in shutdown
                                                pool.pools['dbPool'].stopReaping = True
                                            KeyError: 'dbPool'
19:50:35 T:2744  NOTICE: Before pools
19:50:35 T:2744  NOTICE: Before logging shutdown
19:50:35 T:2744  NOTICE: .
19:50:35 T:3672   ERROR: CLocalizeStrings::ClearBlock: Trying to clear non 
existent block C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox
19:50:36 T:3184 WARNING: XFILE::CFactoryDirectory::Create - Unsupported 
protocol(script) in script://
19:50:36 T:3672   ERROR: Unable to locate window with id -10000.  Check skin 
files
19:50:45 T:3672  NOTICE: Storing total System Uptime
19:50:45 T:3672  NOTICE: Saving settings
19:50:45 T:3672  NOTICE: stop all
19:50:46 T:1504  NOTICE: VideoInfoScanner: Finished scan. Scanning for video 
info took 06:32
19:50:46 T:3672  NOTICE: ES: Stopping event server
19:50:46 T:3672  NOTICE: stopping zeroconf publishing
19:50:47 T:2164  NOTICE: ES: UDP Event server stopped
19:50:47 T:3672  NOTICE: stop sap announcement listener
19:50:47 T:3672  NOTICE: clean cached files!
19:50:47 T:3672  NOTICE: unload skin
19:50:47 T:3672   ERROR: CLocalizeStrings::ClearBlock: Trying to clear non 
existent block C:\Users\cpadmin\AppData\Roaming\XBMC\addons\script.mythbox
19:50:47 T:3672   ERROR: Previous line repeats 3 times.
19:50:47 T:3672 WARNING: CGUITextureManager::Cleanup: Having to cleanup texture 
button-nofocus.png
19:50:47 T:3672 WARNING: CGUITextureManager::Cleanup: Having to cleanup texture 
loading.gif
19:50:47 T:3672 WARNING: CGUITextureManager::Cleanup: Having to cleanup texture 
diffuse_mirror2.png
19:50:47 T:3672 WARNING: CGUITextureManager::Cleanup: Having to cleanup texture 
mb-folder-focus.png
19:50:47 T:3672  NOTICE: stop python
19:50:47 T:3672  NOTICE: stopped
19:50:47 T:3672  NOTICE: destroy
19:50:47 T:3672  NOTICE: closing down remote control service
19:50:47 T:3672  NOTICE: unload sections
19:50:48 T:3672  NOTICE: destroy
19:50:48 T:3672 WARNING: Attempted to remove window 10013 from the window 
manager when it didn't exist
19:50:48 T:3672 WARNING: Attempted to remove window 10014 from the window 
manager when it didn't exist
19:50:48 T:3672 WARNING: Attempted to remove window 10015 from the window 
manager when it didn't exist
19:50:48 T:3672 WARNING: Attempted to remove window 10016 from the window 
manager when it didn't exist
19:50:48 T:3672 WARNING: Attempted to remove window 10017 from the window 
manager when it didn't exist
19:50:48 T:3672 WARNING: Attempted to remove window 10018 from the window 
manager when it didn't exist
19:50:48 T:3672 WARNING: Attempted to remove window 10019 from the window 
manager when it didn't exist
19:50:48 T:3672 WARNING: Attempted to remove window 10107 from the window 
manager when it didn't exist
19:50:48 T:3672 WARNING: Attempted to remove window 10115 from the window 
manager when it didn't exist
19:50:48 T:3672 WARNING: Attempted to remove window 10104 from the window 
manager when it didn't exist
19:50:48 T:3672  NOTICE: closing down remote control service
19:50:48 T:3672  NOTICE: unload sections
19:50:48 T:3672  NOTICE: application stopped...

```

Original issue reported on code.google.com by `ThirstyL...@gmail.com` on 6 Jun 2012 at 12:34

**Comment by GoogleCodeExporter** [comment]
```
Same problem.  But how can I downgrade to .24?  I have mythbuntu installed and 
it automatically installed mythtv
```

Original comment by `stevedaw...@gmail.com` on 26 Jul 2012 at 5:03

**Comment by GoogleCodeExporter** [comment]
```
Not really the place for this discussion but here is how to downgrade to .24 if 
you have to: http://www.mythtv.org/pipermail/mythtv-users/2012-May/333230.html

Not really recommended.
```

Original comment by `ThirstyL...@gmail.com` on 31 Jul 2012 at 5:05
