### ISSUE TITLE
Recording fails to play against MythTV 0.25

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/mythbox#213]
```
What steps will reproduce the problem?
1.  Launch MythBox
2.  Choose a recording
3.  Choose Play

What is the expected output? What do you see instead?
Expecting to see the recording to play.  Instead, MythBox stays on the same 
page, I can click on Play again - same result.


What version of the product are you using? On what operating system?

I am running on an AppleTV 1.

MythBox analogue-mythbox-1.0.4-124-gc94cff4.zip

Darwin AppleTV-4.local 8.8.2 Darwin Kernel Version 8.8.2: Mon Jan 29 18:57:29 
PST 2007; root:xnu-792.94.18~1/RELEASE_I386 i386 i386

-bash-2.05b$ sw_vers
ProductName:    Apple TV OS
ProductVersion: 10.4.7
BuildVersion:   8N6014

XBMC Eden 11.0 


Please provide any additional information below.

I can play the video using Myth Frontend and MythWeb.

I turned on the debug log for XBMC Eden 11.0 and MythBox 1.0.4.  


Here is the mythbackend.log

Jul  4 21:39:12 myth mythbackend[6156]: C ProcessRequest mainserver.cpp:1259 
(HandleVersion) MainServer::HandleVersion - Client speaks protocol version 8 
but we speak 72!
Jul  4 21:39:12 myth mythbackend[6156]: W ProcessRequest mainserver.cpp:5801 
(connectionClosed) MainServer: Unknown socket closing MythSocket(0xb762b0)
Jul  4 21:39:12 myth mythbackend[6156]: W Socket mainserver.cpp:5801 
(connectionClosed) MainServer: Unknown socket closing MythSocket(0xc53090)



Here is the section from me pressing the Play button in MythBox.

xbmc.log

21:39:12 T:61090816   DEBUG: recordingdetails.py:195 | MainThread | Playing 
with skip Frozen Planet ..
21:39:12 T:61090816   DEBUG: player.py:198 | MainThread | > playRecording 
Frozen Planet
21:39:12 T:61090816   DEBUG: player.py:190 | MainThread | Playback url: 
myth://mythconverg:***@192.168.1.40:6543/recordings/1040_20120428010000.mpg
21:39:12 T:61090816   DEBUG: player.py:202 | MainThread | < playRecording
21:39:12 T:61090816   DEBUG: recordingdetails.py:245 | MainThread | onAction 7
21:39:12 T:61090816   DEBUG: recordingdetails.py:258 | MainThread | unhandled 
action = <xbmcgui.Action object at 0xea019a0>  id = 7
21:39:12 T:2684407808   DEBUG: 
CPlayerCoreFactory::GetPlayers(myth://mythconverg:***@192.168.1.40:6543/recordin
gs/1040_20120428010000.mpg)
21:39:12 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: considering 
rule: system rules
21:39:12 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: 
system rules
21:39:12 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: considering 
rule: rtv
21:39:12 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: considering 
rule: hdhomerun/myth/rtmp/mms/udp
21:39:12 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: 
hdhomerun/myth/rtmp/mms/udp
21:39:12 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: adding player: 
DVDPlayer (1) for rule: hdhomerun/myth/rtmp/mms/udp
21:39:12 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: considering 
rule: lastfm/shout
21:39:12 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: considering 
rule: rtsp
21:39:12 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: considering 
rule: streams
21:39:12 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: considering 
rule: dvd
21:39:12 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: considering 
rule: dvdfile
21:39:12 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: considering 
rule: dvdimage
21:39:12 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: considering 
rule: sdp/asf
21:39:12 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: considering 
rule: nsv
21:39:12 T:2684407808   DEBUG: CPlayerCoreFactory::GetPlayers: matched 1 rules 
with players
21:39:12 T:2684407808   DEBUG: CPlayerCoreFactory::GetPlayers: adding 
videodefaultplayer (1)
21:39:12 T:2684407808   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, 
audio=0
21:39:12 T:2684407808   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, 
audio=1
21:39:12 T:2684407808   DEBUG: CPlayerCoreFactory::GetPlayers: adding player: 
DVDPlayer (1)
21:39:12 T:2684407808   DEBUG: CPlayerCoreFactory::GetPlayers: added 1 players
21:39:12 T:2684407808   DEBUG: CGUIAudioManager::DeInitialize
21:39:13 T:2684407808  NOTICE: DVDPlayer: Opening: 
myth://mythconverg:***@192.168.1.40:6543/recordings/1040_20120428010000.mpg
21:39:13 T:2684407808 WARNING: CDVDMessageQueue(player)::Put 
MSGQ_NOT_INITIALIZED
21:39:13 T:2684407808   DEBUG: CRenderManager::UpdateDisplayLatency - Latency 
set to 0 msec
21:39:13 T:2684407808   DEBUG: LinuxRendererGL: Cleaning up GL resources
21:39:13 T:61620736   DEBUG: Thread CDVDPlayer start, auto delete: 0
21:39:13 T:61620736  NOTICE: Creating InputStream
21:39:13 T:61620736   DEBUG: AquireSession - Aquired existing MythTV session: 
0xce09b20
21:39:13 T:2684407808   DEBUG: ------ Window Init (DialogBusy.xml) ------
21:39:13 T:61620736   ERROR: (cmyth)cmyth_conn_connect: asked for version 8, 
got version 72
21:39:13 T:61620736   ERROR: (cmyth)cmyth_conn_connect: failed to connect with 
any version
21:39:13 T:61620736   ERROR: GetControl - unable to connect to server on 
192.168.1.40:6543
21:39:13 T:61620736   DEBUG: ReleaseSession - Releasing MythTV session: 
0xce09b20
21:39:13 T:61620736   ERROR: CDVDPlayer::OpenInputStream - error opening 
[myth://mythconverg:***@192.168.1.40:6543/recordings/1040_20120428010000.mpg]
21:39:13 T:61620736  NOTICE: CDVDPlayer::OnExit()
21:39:13 T:61620736  NOTICE: CDVDPlayer::OnExit() deleting input stream
21:39:13 T:61620736   DEBUG: Thread CDVDPlayer 61620736 terminating
21:39:13 T:61090816   DEBUG: player.py:73 | MainThread | > onPlayBackStopped
21:39:13 T:61090816   ERROR: player.py:78 | MainThread | onPlayBackStopped
                                            Traceback (most recent call last):
                                              File "/Users/frontrow/Library/Application Support/XBMC/addons/script.mythbox/resources/src/mythbox/ui/player.py", line 76, in onPlayBackStopped
                                                target.onPlayBackStopped()
                                              File "/Users/frontrow/Library/Application Support/XBMC/addons/script.mythbox/resources/src/mythbox/ui/player.py", line 312, in onPlayBackStopped
                                                if self._tracker.isAlive():
                                            AttributeError: 'BoundedEvictingQueue' object has no attribute 'isAlive'
21:39:13 T:61090816   DEBUG: player.py:282 | MainThread | Setting bookmark on 
Frozen Planet to 0s
21:39:13 T:61090816   DEBUG: conn.py:877 | MainThread | Bookmark frameNumber 
set to 0
21:39:13 T:61090816   DEBUG: player.py:79 | MainThread | < onPlayBackStopped
21:39:13 T:2684407808   DEBUG: CAnnouncementManager - Announcement: OnStop from 
xbmc
21:39:13 T:2684407808   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message 
OnStop
21:39:13 T:2684407808  NOTICE: CDVDPlayer::CloseFile()
21:39:13 T:2684407808 WARNING: CDVDMessageQueue(player)::Put 
MSGQ_NOT_INITIALIZED
21:39:13 T:2684407808  NOTICE: CDVDPlayer::CloseFile()
21:39:13 T:2684407808 WARNING: CDVDMessageQueue(player)::Put 
MSGQ_NOT_INITIALIZED
21:39:13 T:2684407808  NOTICE: DVDPlayer: waiting for threads to exit
21:39:13 T:2684407808  NOTICE: DVDPlayer: finished waiting
21:39:13 T:2684407808   DEBUG: LinuxRendererGL: Cleaning up GL resources
21:39:13 T:63845376   DEBUG: publish.py:61 | Thread-8 | EVENT: 
[u'BACKEND_MESSAGE', u'RECORDING_LIST_CHANGE UPDATE', u'Frozen Planet', u'On 
Thin Ice', u'Naturalist David Attenborough offers a view of what rising 
temperatures will mean for the people and wildlife of the North and South 
poles.', u'0', u'0', u'Nature', u'1040', u'42', u'TDCC', u'The Discovery 
Channel Canada', u'1040_20120428010000.mpg', u'2333206528', u'1335589200', 
u'1335592800', u'734986', u'myth', u'0', u'0', u'0', u'18', u'-3', u'1033', 
u'0', u'15', u'6', u'1335589200', u'1335592800', u'4101', u'DavesCrap', u'', 
u'EP01523600', u'EP015236000007', u'', u'1341452448', u'0', u'2012-04-22', 
u'Adult', u'0', u'0', u'Default', u'1', u'0', u'1', u'0']
21:39:13 T:2684407808   DEBUG: CGUIAudioManager::Initialize
21:39:13 T:2684407808   DEBUG: ------ Window Deinit (DialogBusy.xml) ------


Any suggestions or work arounds?

Thanks,
Dave



```

Original issue reported on code.google.com by `DFishb...@gmail.com` on 5 Jul 2012 at 2:44

**Comment by GoogleCodeExporter** [comment]
```
I missed a part of the debug comments from the xbmc.log.

I don't know if these 2 lines are important:
22:50:39 T:2684407808   DEBUG: Building didl for object 
'myth://mythconverg:***@192.168.1.40:6543/recordings/1040_20120428010000.mpg'
22:50:39 T:2684407808   ERROR: Incorrect movie stacking regexp format:[(.*?)([ 
._-]*[a-d])(.*?)(\.[^.]+)$]



Here is the full section from my hitting Play.




22:50:30 T:2684407808   DEBUG: ------ Window Init 
(/Users/frontrow/Library/Application 
Support/XBMC/addons/script.mythbox/resources/skins/Default/720p/mythbox_recordin
g_details.xml) ------
22:50:30 T:2684407808    INFO: Loading skin file: 
/Users/frontrow/Library/Application 
Support/XBMC/addons/script.mythbox/resources/skins/Default/720p/mythbox_recordin
g_details.xml
22:50:30 T:62934528   DEBUG: recordings.py:200 | MainThread | uncaught action 
id 7
22:50:31 T:2684407808   ERROR: Texture manager unable to load file: 
/Users/frontrow/Library/Application 
Support/XBMC/userdata/addon_data/script.mythbox/cache/channel/
22:50:31 T:64046592   DEBUG: db.py:427 | Thread-19 | FPS actual   1.9964
22:50:31 T:64046592   DEBUG: db.py:428 | Thread-19 | FPS duration 1.9964
22:50:31 T:64046592   DEBUG: conn.py:926 | Thread-19 | 6 commercials in Frozen 
Planet
22:50:32 T:61470208   DEBUG: Thread Jobworker 61470208 terminating (autodelete)
22:50:32 T:61155328   DEBUG: Thread Jobworker 61155328 terminating (autodelete)
22:50:38 T:61414912   DEBUG: Thread Jobworker 61414912 terminating (autodelete)
22:50:39 T:62934528   DEBUG: recordingdetails.py:266 | MainThread | onClick 251
22:50:39 T:62934528   DEBUG: recordingdetails.py:195 | MainThread | Playing 
with skip Frozen Planet ..
22:50:39 T:62934528   ERROR: /Users/frontrow/Library/Application 
Support/XBMC/addons/script.mythbox/resources/src/mythbox/ui/player.py:46: 
DeprecationWarning: object.__init__() takes no parameters
                                              xbmc.Player.__init__(self, *args, **kwargs)
22:50:39 T:62934528   DEBUG: player.py:198 | MainThread | > playRecording 
Frozen Planet
22:50:39 T:62934528   DEBUG: player.py:190 | MainThread | Playback url: 
myth://mythconverg:***@192.168.1.40:6543/recordings/1040_20120428010000.mpg
22:50:39 T:62934528   DEBUG: player.py:202 | MainThread | < playRecording
22:50:39 T:62934528   DEBUG: recordingdetails.py:245 | MainThread | onAction 7
22:50:39 T:62934528   DEBUG: recordingdetails.py:258 | MainThread | unhandled 
action = <xbmcgui.Action object at 0xd5be240>  id = 7
22:50:39 T:2684407808   DEBUG: 
CPlayerCoreFactory::GetPlayers(myth://mythconverg:***@192.168.1.40:6543/recordin
gs/1040_20120428010000.mpg)
22:50:39 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: considering 
rule: system rules
22:50:39 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: 
system rules
22:50:39 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: considering 
rule: rtv
22:50:39 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: considering 
rule: hdhomerun/myth/rtmp/mms/udp
22:50:39 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: 
hdhomerun/myth/rtmp/mms/udp
22:50:39 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: adding player: 
DVDPlayer (1) for rule: hdhomerun/myth/rtmp/mms/udp
22:50:39 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: considering 
rule: lastfm/shout
22:50:39 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: considering 
rule: rtsp
22:50:39 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: considering 
rule: streams
22:50:39 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: considering 
rule: dvd
22:50:39 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: considering 
rule: dvdfile
22:50:39 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: considering 
rule: dvdimage
22:50:39 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: considering 
rule: sdp/asf
22:50:39 T:2684407808   DEBUG: CPlayerSelectionRule::GetPlayers: considering 
rule: nsv
22:50:39 T:2684407808   DEBUG: CPlayerCoreFactory::GetPlayers: matched 1 rules 
with players
22:50:39 T:2684407808   DEBUG: CPlayerCoreFactory::GetPlayers: adding 
videodefaultplayer (1)
22:50:39 T:2684407808   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, 
audio=0
22:50:39 T:2684407808   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, 
audio=1
22:50:39 T:2684407808   DEBUG: CPlayerCoreFactory::GetPlayers: adding player: 
DVDPlayer (1)
22:50:39 T:2684407808   DEBUG: CPlayerCoreFactory::GetPlayers: added 1 players
22:50:39 T:2684407808   DEBUG: CGUIAudioManager::DeInitialize
22:50:39 T:2684407808  NOTICE: DVDPlayer: Opening: 
myth://mythconverg:***@192.168.1.40:6543/recordings/1040_20120428010000.mpg
22:50:39 T:2684407808 WARNING: CDVDMessageQueue(player)::Put 
MSGQ_NOT_INITIALIZED
22:50:39 T:2684407808   DEBUG: CRenderManager::UpdateDisplayLatency - Latency 
set to 0 msec
22:50:39 T:2684407808   DEBUG: LinuxRendererGL: Cleaning up GL resources
22:50:39 T:2684407808   DEBUG: 
SECTION:LoadDLL(special://xbmcbin/system/players/dvdplayer/avutil-50-x86-osx.so)
22:50:39 T:2684407808   DEBUG: Loading: 
/mnt/Scratch/Users/frontrow/Applications/XBMC.app/Contents/Resources/XBMC/system
/players/dvdplayer/avutil-50-x86-osx.so
22:50:39 T:2684407808   DEBUG: 
SECTION:LoadDLL(special://xbmcbin/system/players/dvdplayer/swscale-0-x86-osx.so)
22:50:39 T:2684407808   DEBUG: Loading: 
/mnt/Scratch/Users/frontrow/Applications/XBMC.app/Contents/Resources/XBMC/system
/players/dvdplayer/swscale-0-x86-osx.so
22:50:39 T:60532224   DEBUG: Thread CDVDPlayer start, auto delete: 0
22:50:39 T:60532224  NOTICE: Creating InputStream
22:50:39 T:60532224   DEBUG: 
SECTION:LoadDLL(special://xbmcbin/system/libcmyth-x86-osx.so)
22:50:39 T:60532224   DEBUG: Loading: 
/mnt/Scratch/Users/frontrow/Applications/XBMC.app/Contents/Resources/XBMC/system
/libcmyth-x86-osx.so
22:50:39 T:60532224    INFO: AquireSession - Aquired new MythTV session for 
myth://192.168.1.40:6543/recordings/1040_20120428010000.mpg: 0x9faf740
22:50:39 T:2684407808   DEBUG: ------ Window Init (DialogBusy.xml) ------
22:50:39 T:2684407808   DEBUG: Building didl for object 
'myth://mythconverg:***@192.168.1.40:6543/recordings/1040_20120428010000.mpg'
22:50:39 T:2684407808   ERROR: Incorrect movie stacking regexp format:[(.*?)([ 
._-]*[a-d])(.*?)(\.[^.]+)$]
22:50:40 T:60532224   ERROR: Previous line repeats 1 times.
22:50:40 T:60532224   ERROR: (cmyth)cmyth_conn_connect: asked for version 8, 
got version 72
22:50:40 T:60532224   ERROR: (cmyth)cmyth_conn_connect: failed to connect with 
any version
22:50:40 T:60532224   ERROR: GetControl - unable to connect to server on 
192.168.1.40:6543
22:50:40 T:60532224   DEBUG: ReleaseSession - Releasing MythTV session: 
0x9faf740
22:50:40 T:60532224   ERROR: CDVDPlayer::OpenInputStream - error opening 
[myth://mythconverg:***@192.168.1.40:6543/recordings/1040_20120428010000.mpg]
22:50:40 T:60532224  NOTICE: CDVDPlayer::OnExit()
22:50:40 T:60532224  NOTICE: CDVDPlayer::OnExit() deleting input stream
22:50:40 T:60532224   DEBUG: Thread CDVDPlayer 60532224 terminating
22:50:40 T:62934528   DEBUG: player.py:73 | MainThread | > onPlayBackStopped
22:50:40 T:62934528   ERROR: player.py:78 | MainThread | onPlayBackStopped
                                            Traceback (most recent call last):
                                              File "/Users/frontrow/Library/Application Support/XBMC/addons/script.mythbox/resources/src/mythbox/ui/player.py", line 76, in onPlayBackStopped
                                                target.onPlayBackStopped()
                                              File "/Users/frontrow/Library/Application Support/XBMC/addons/script.mythbox/resources/src/mythbox/ui/player.py", line 312, in onPlayBackStopped
                                                if self._tracker.isAlive():
                                            AttributeError: 'BoundedEvictingQueue' object has no attribute 'isAlive'
22:50:40 T:62934528   DEBUG: player.py:282 | MainThread | Setting bookmark on 
Frozen Planet to 0s
22:50:40 T:62934528   DEBUG: conn.py:877 | MainThread | Bookmark frameNumber 
set to 0
22:50:40 T:62934528   DEBUG: player.py:79 | MainThread | < onPlayBackStopped
22:50:40 T:2684407808   DEBUG: CAnnouncementManager - Announcement: OnStop from 
xbmc
22:50:40 T:2684407808   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message 
OnStop
22:50:40 T:2684407808  NOTICE: CDVDPlayer::CloseFile()
22:50:40 T:2684407808 WARNING: CDVDMessageQueue(player)::Put 
MSGQ_NOT_INITIALIZED
22:50:40 T:2684407808  NOTICE: DVDPlayer: waiting for threads to exit
22:50:40 T:2684407808  NOTICE: DVDPlayer: finished waiting
22:50:40 T:2684407808   DEBUG: LinuxRendererGL: Cleaning up GL resources
22:50:40 T:2684407808   DEBUG: CGUIAudioManager::Initialize
22:50:40 T:63931392   DEBUG: publish.py:61 | Thread-8 | EVENT: 
[u'BACKEND_MESSAGE', u'RECORDING_LIST_CHANGE UPDATE', u'Frozen Planet', u'On 
Thin Ice', u'Naturalist David Attenborough offers a view of what rising 
temperatures will mean for the people and wildlife of the North and South 
poles.', u'0', u'0', u'Nature', u'1040', u'42', u'TDCC', u'The Discovery 
Channel Canada', u'1040_20120428010000.mpg', u'2333206528', u'1335589200', 
u'1335592800', u'734986', u'myth', u'0', u'0', u'0', u'18', u'-3', u'1033', 
u'0', u'15', u'6', u'1335589200', u'1335592800', u'4101', u'DavesCrap', u'', 
u'EP01523600', u'EP015236000007', u'', u'1341456735', u'0', u'2012-04-22', 
u'Adult', u'0', u'0', u'Default', u'1', u'0', u'1', u'0']
22:50:40 T:2684407808   DEBUG: ------ Window Deinit (DialogBusy.xml) ------



```

Original comment by `DFishb...@gmail.com` on 5 Jul 2012 at 2:58

**Comment by GoogleCodeExporter** [comment]
```
Is there a Wiki entry specifically for setting up MythBox for debugging?

I know how busy people are to look at these issues, so I can always have a 
first cut at it.  I found a generic wiki page for setting up Eclipse for Python 
debugging with XBMC.  Though it references Eclipse 3.x, and the current is 4.x.

Any help is appreciated.

Thanks,
Dave
```

Original comment by `DFishb...@gmail.com` on 5 Jul 2012 at 11:50

**Comment by GoogleCodeExporter** [comment]
```
This problem is specific to Linux -- perhaps Debian or Ubuntu (I am using 11.10 
Ubuntu) -- it occurs when configured to stream the content vs using local or a 
network filesystem (e.g. NFS or SMB/CIFS).  It appears to be related to util.py 
and 'BoundedEvictingQueue' object has no attribute 'isAlive'.  I notice that it 
does not happen on my OSX machine, which is able to play streams just fine.  I 
note that when my Ubuntu frontends try to stream, an example error condition on 
the backend being connected to is:

2012-08-31 00:56:54.578877 W [2431/2474] Socket mainserver.cpp:5789 
(connectionClosed) - MainServer: Unknown socket closing MythSocket(0x218ed20)
2012-08-31 00:56:55.597984 C [2431/3521] ProcessRequest mainserver.cpp:1248 
(HandleVersion) - MainServer::HandleVersion - Client speaks protocol version 8 
but we speak 74!
2012-08-31 00:56:55.598051 W [2431/3521] ProcessRequest mainserver.cpp:5789 
(connectionClosed) - MainServer: Unknown socket closing MythSocket(0x2202720)

That said, the same mythbox revision on OSX is able to stream just fine.  I 
looked into the problem a little but have not had time to figure it out.  I 
would be happy to provide more troubleshooting information.  The key bit on the 
XBMC mythbox side is, for example:

01:09:44 T:140315492128512   ERROR: CDVDPlayer::OpenInputStream - error opening 
[myth://mythconverg:mythtv@10.0.10.11:6543/recordings/2025_20120830185800.mpg]
01:09:44 T:140315492128512  NOTICE: CDVDPlayer::OnExit()
01:09:44 T:140315492128512  NOTICE: CDVDPlayer::OnExit() deleting input stream
01:09:44 T:140315267024640   ERROR: player.py:78 | MainThread | 
onPlayBackStopped
                                            Traceback (most recent call last):
                                              File "/home/wylie/.xbmc/addons/script.mythbox/resources/src/mythbox/ui/player.py", line 76, in onPlayBackStopped
                                                target.onPlayBackStopped()
                                              File "/home/wylie/.xbmc/addons/script.mythbox/resources/src/mythbox/ui/player.py", line 312, in onPlayBackStopped
                                                if self._tracker.isAlive():
                                            AttributeError: 'BoundedEvictingQueue' object has no attribute 'isAlive'
01:09:44 T:140315812681600  NOTICE: CDVDPlayer::CloseFile()



```

Original comment by `Wylie.Sw...@gmail.com` on 31 Aug 2012 at 8:20

**Comment by GoogleCodeExporter** [comment]
```
Further, an example of similar content working just fine from an OSX XBMC 
frontend and the same backend:

00:51:47 T:2894801448  NOTICE: DVDPlayer: Opening: 
http://10.0.10.15/mythtv/recordings/2121_20120819210000.mpg
00:51:47 T:2894801448 WARNING: CDVDMessageQueue(player)::Put 
MSGQ_NOT_INITIALIZED
00:51:47 T:2953318400  NOTICE: Creating InputStream
00:51:47 T:2953318400  NOTICE: Creating Demuxer
00:51:47 T:2953318400  NOTICE: Opening video stream: 0 source: 256
00:51:47 T:2953318400  NOTICE: Creating video codec with codec id: 2
00:51:47 T:2953318400  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: MPEG-2 
video
00:51:47 T:2953318400  NOTICE: Creating video thread
00:51:47 T:2953318400  NOTICE: Opening audio stream: 1 source: 256
00:51:47 T:2968371200  NOTICE: running thread: video_thread
00:51:47 T:2953318400  NOTICE: Finding audio codec for: 86019
00:51:47 T:2953318400  NOTICE: Creating audio thread
00:51:47 T:2971566080  NOTICE: running thread: CDVDPlayerAudio::Process()
00:51:47 T:2971566080  NOTICE: Creating audio device with codec id: 86019, 
channels: 6, sample rate: 48000, no pass-through

```

Original comment by `Wylie.Sw...@gmail.com` on 31 Aug 2012 at 8:25

**Comment by GoogleCodeExporter** [comment]
```
i have same problem with my system.
http://forum.xbmc.org/showthread.php?tid=43115&pid=1181987#pid1181987

does nobody know how to fix it?
```

Original comment by `tkh...@gmail.com` on 5 Sep 2012 at 1:50
