### ISSUE TITLE
MythBox won't start since XBMC 9.04.3 svn 23164 on Ubuntu 9.04 Jaunty

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/mythbox#60]
```
What steps will reproduce the problem?
1. When starting the mythbox script


What is the expected output? What do you see instead?
Instead, I receive this window error message:

Initializing stage 3
'textYOffset' is an invalid keyword argument for this function

What version of the product are you using? On what operating system?
MythBox Beta SVN 1260 with XBMC 9.04.3 SVN 23164 on Ubuntu 9.04 Jaunty

Please provide any additional information below.
It was working very well before with XBMC 9.04


```

Original issue reported on code.google.com by `wayne.ve...@gmail.com` on 28 Sep 2009 at 1:15

**Comment by GoogleCodeExporter** [comment]
```
Here is a copy of mythbox.log:
DEBUG | mythtv.core | default.py | MainThread | Line 104 | Mythbox Logger 
Initialized
INFO | mythtv.core | default.py | MainThread | Line 296 | 

        Initializing...


INFO | mythtv.core | util.py | MainThread | Line 516 |  ============ MythBox 
Started 
================
INFO | mythtv.core | default.py | MainThread | Line 299 | ---===[ MythBox 
Version: [Beta SVN 1260] ]===--
-
DEBUG | mythtv.core | default.py | MainThread | Line 310 | 
===================================================================
=============
hostname        = brassia
platform        = UnixPlatform 
script dir      = /home/veilleux/.xbmc/scripts/MythBox
script data dir = /home/veilleux/.xbmc/userdata/script_data/MythBox
===================================================================
=============
DEBUG | mythtv.core | default.py | MainThread | Line 148 | Update available = 
<Thread(Thread-1, started)>
WARNING | mythtv.core | updater.py | Thread-1 | Line 42 | Failed to check for 
updates
DEBUG | mythtv.core | mythdb.py | MainThread | Line 79 | Initializing myth 
database connection
DEBUG | mythtv.perf | util.py | MainThread | Line 233 | TIMER: initialise took 
0.14 seconds
DEBUG | mythtv.core | mythdb.py | MainThread | Line 90 | Closing db connection
DEBUG | mythtv.core | mythtv.py | MainThread | Line 103 | 
Connection.connect(False,True)
DEBUG | mythtv.core | mythtv.py | MainThread | Line 110 | Getting server 
version...
DEBUG | mythtv.core | mythtv.py | MainThread | Line 136 | getServerVersion: 
REJECT 40
DEBUG | mythtv.core | mythtv.py | MainThread | Line 112 | Server version = 40
DEBUG | mythtv.perf | util.py | MainThread | Line 233 | TIMER: _initialise took 
0.25 seconds
ERROR | mythtv.core | default.py | MainThread | Line 390 | Initializing stage 3
Traceback (most recent call last):
  File "/home/veilleux/.xbmc/scripts/MythBox/default.py", line 371, in ?
    win.loadskin("home.xml")
  File "<string>", line 1, in <lambda>
  File "/home/veilleux/.xbmc/scripts/MythBox/resources/src/util.py", line 227, in timed
    result = func(*args, **kw)
  File "/home/veilleux/.xbmc/scripts/MythBox/resources/src/skin.py", line 310, in loadskin
    self.addcontrols(dom.getElementsByTagName("control"))
  File "/home/veilleux/.xbmc/scripts/MythBox/resources/src/skin.py", line 357, in addcontrols
    me.create()
  File "/home/veilleux/.xbmc/scripts/MythBox/resources/src/skin.py", line 152, in create
    alignment=align)
TypeError: 'textYOffset' is an invalid keyword argument for this function


```

Original comment by `wayne.ve...@gmail.com` on 28 Sep 2009 at 1:46

**Comment by GoogleCodeExporter** [comment]
```
This patch may help. 

To apply,

cd /path/to/mythbox

patch -p1 < /path/to/patch

YMMV
```

Original comment by `steveno...@gmail.com` on 30 Sep 2009 at 7:30

Attachments:
- [mythbox-fix-control-offsets.patch](https://storage.googleapis.com/google-code-attachments/mythbox/issue-60/comment-2/mythbox-fix-control-offsets.patch)

**Comment by GoogleCodeExporter** [comment]
```
Works like a charm for me with the patch! Thanks!
```

Original comment by `oscar.fo...@gmail.com` on 6 Oct 2009 at 7:54

**Comment by GoogleCodeExporter** [comment]
```
Fixed in svn 1510
```

Original comment by `semir.pa...@gmail.com` on 17 Oct 2009 at 5:48
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Issue 65 has been merged into this issue.
```

Original comment by `semir.pa...@gmail.com` on 21 Oct 2009 at 1:14
